Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-10, with the labels that each got.

#365 Fix the type of the ListenerStatus.Port.
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#336 API Validation and Cleanup
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/forwarding_target_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/local_object_reference_types.go
  apis/v1alpha1/route_extension_reference_types.go
  apis/v1alpha1/route_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/basic-http.yaml
  examples/basic-udp.yaml
  examples/default-match-http.yaml
  examples/http-trafficsplit.yaml
  examples/multiple-https.yaml
  examples/multiple-tcp.yaml
  examples/tls-in-route.yaml
  examples/wildcard-https.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#368 Updates Dev Docs
  docs-src/devguide.md
  docs/devguide/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#369 Specify printer columns for gateway, gatewayclass, httproute #354
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#366 deprecate the feedback page update issue link
  docs-src/community.md
  docs-src/feedback.md
  docs-src/index.md
  docs/404.html
  docs/community/index.html
  docs/concepts/index.html
  docs/cookbook/index.html
  docs/devguide/index.html
  docs/enhancement-requests/index.html
  docs/faq/index.html
  docs/feedback/index.html
  docs/index.html
  docs/releases/index.html
  docs/security-model/index.html
  docs/spec/index.html
  docs/userguide/index.html
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#372 Consistently apply list-map typing to Conditions slices.
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/route_types.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#360 Changing Resource to Kind, Removing Defaults for Group and Kind
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/local_object_reference_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/backendpolicy.yaml
  examples/basic-http.yaml
  examples/basic-tcp.yaml
  examples/basic-udp.yaml
  examples/default-match-http.yaml
  examples/http-trafficsplit.yaml
  examples/multiple-https.yaml
  examples/multiple-tcp.yaml
  examples/single-http.yaml
  examples/tls-in-route.yaml
  examples/wildcard-http.yaml
  examples/wildcard-https.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#352 Fix codegen script to work with Go modules.
  Makefile
  go.mod
  go.sum
  hack/update-codegen.sh
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/listers/apis/v1alpha1/backendpolicy.go
  pkg/client/listers/apis/v1alpha1/gateway.go
  pkg/client/listers/apis/v1alpha1/gatewayclass.go
  pkg/client/listers/apis/v1alpha1/httproute.go
  pkg/client/listers/apis/v1alpha1/tcproute.go
  pkg/client/listers/apis/v1alpha1/tlsroute.go
  pkg/client/listers/apis/v1alpha1/udproute.go
  tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#373 httproute: remove extension points in spec
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#377 Delete the unused ListenerExtensionObjectReference.
  apis/v1alpha1/gateway_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#362 Updating RouteNamespaces to use RouteGateways pattern
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/basic-http.yaml
  examples/basic-tcp.yaml
  examples/basic-udp.yaml
  examples/default-match-http.yaml
  examples/http-trafficsplit.yaml
  examples/multiple-https.yaml
  examples/multiple-tcp.yaml
  examples/single-http.yaml
  examples/tls-in-route.yaml
  examples/wildcard-http.yaml
  examples/wildcard-https.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#364 Updates Request Workflow in Docs
  docs-src/concepts.md
  docs/concepts/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#371 Update Listener condition types.
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#381 remove dependency on kustomize binary
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#383 remove hardcoded resources in delete-crds.sh
  hack/delete-crds.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#382 fix kustomization to actually install backendpolicy
  config/crd/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#376 Decreasing min weight from 1 to 0
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#379 Clean up match type and add regex header match
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#378 Change type alias to creating a new type
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/httproute_types.go
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#384 clean up community doc to removec outdated links
  docs-src/community.md
  docs/community/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#387 docs: change paremetersRef to use CRD
  docs-src/concepts.md
  docs/concepts/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#380 clean up dev guide
  docs-src/devguide.md
  docs/devguide/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#389 fix indents and sections headers in concepts
  docs-src/concepts.md
  docs/concepts/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#393 mkdocs: add mkdocs-macros-plugin for embedding yaml files
  mkdocs.requirements.txt
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#400 drop clientCertificateRef from backendpolicy
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#397 gateway: simplify route selection naming
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/basic-http.yaml
  examples/basic-tcp.yaml
  examples/basic-udp.yaml
  examples/default-match-http.yaml
  examples/http-trafficsplit.yaml
  examples/multiple-https.yaml
  examples/multiple-tcp.yaml
  examples/single-http.yaml
  examples/tls-in-route.yaml
  examples/wildcard-http.yaml
  examples/wildcard-https.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#388 document extension concept
  docs-src/concepts.md
  docs/concepts/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#385 add recommendation to add finalizer to GatewayClass
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#394 default to Same namespace in route selection
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#402 Removing allowedGatewayNamespaces from GatewayClass
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  docs-src/security-model.md
  docs-src/spec.md
  docs/security-model/index.html
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#391 add document elaborating on how to use TLS and examples
  docs-src/concepts.md
  docs-src/tls-overview.svg
  docs-src/tls.md
  docs/concepts/index.html
  docs/tls-overview.svg
  docs/tls/index.html
  examples/multiple-https.yaml
  examples/tls-basic.yaml
  examples/tls-cert-in-route.yaml
  examples/upstream-tls.yaml
  examples/wildcard-tls-gateway.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#406 docs: reorganize nav bar
  docs-src/enhancement-requests.md
  docs/404.html
  docs/community/index.html
  docs/concepts/index.html
  docs/cookbook/index.html
  docs/devguide/index.html
  docs/enhancement-requests/index.html
  docs/faq/index.html
  docs/index.html
  docs/releases/index.html
  docs/security-model/index.html
  docs/spec/index.html
  docs/tls/index.html
  docs/userguide/index.html
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#417 Add reviewers {bowei,robscott,hbagdi,jpeach,danehans}
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#419 Installing golint if it doesn't exist
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#420 Fixing verify-golint by using mod=readonly go flag
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#422 make port a required field
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  docs/tls/index.html
  examples/basic-http.yaml
  examples/basic-tcp.yaml
  examples/basic-udp.yaml
  examples/default-match-http.yaml
  examples/http-trafficsplit.yaml
  examples/tls-cert-in-route.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#423 define a new Go type Port for consolidation
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#408 Updates Filter Naming and Docs
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/http-filter.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#398 future proof open-ended ProtocolType
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#425 multiple cleanups in docs
  docs-src/concepts.md
  docs-src/cookbook.md
  docs-src/guides.md
  docs-src/index.md
  docs-src/security-model.md
  docs-src/userguide.md
  docs/404.html
  docs/community/index.html
  docs/concepts/index.html
  docs/cookbook/index.html
  docs/devguide/index.html
  docs/enhancement-requests/index.html
  docs/faq/index.html
  docs/guides/index.html
  docs/index.html
  docs/releases/index.html
  docs/security-model/index.html
  docs/spec/index.html
  docs/tls/index.html
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#428 Adding a way to verify examples with kind, fixing BackendPolicy example
  examples/backendpolicy.yaml
  examples/default-match-http.yaml
  examples/http-filter.yaml
  hack/verify-examples-kind.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#424 document the release process
  CHANGELOG.md
  RELEASE.md
  docs-src/devguide.md
  docs/devguide/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#432 remove verify-examples.sh and go script
  examples/examples_test.go
  hack/verify-examples.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#439 change max items from 10 to 16 for snis in TLSRoute
  apis/v1alpha1/tlsroute_types.go
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#438 revamp readme to point to relevant resources
  LICENSE
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#441 remove outdated PROJECT file
  PROJECT
Labels: approved, cncf-cla: yes, lgtm, size/S

#442 correct links to website content
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#429 Updates NamedAddressType and IPAddressType Godocs
  apis/v1alpha1/gateway_types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#437 docs: implementations MAY collapse listeners
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
