Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-02, with the labels that each got.

#47 Making Gateway Status more descriptive
  api/v1alpha1/gateway_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  docs-src/concepts.md
  docs/concepts/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: approved, cncf-cla: yes, lgtm, size/L

#77 Freeze the mkdocs versions
  mkdocs.dockerfile
  mkdocs.requirements.txt
Labels: approved, cncf-cla: yes, lgtm, size/S

#78 Remove sitemap.xml
  docs.mk
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: approved, cncf-cla: yes, lgtm, size/M

#76 Updates Gateway godocs
  api/v1alpha1/gateway_types.go
  config/crd/bases/networking.x.k8s.io_gateways.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#68 Adds ingress request flow to docs
  docs-src/concepts.md
  docs/concepts/index.html
  docs/search/search_index.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#43 Singularizes and expands godocs of HTTPRoute hostname
  api/v1alpha1/httproute_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x.k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#73 Replace ObjectReference, TypedLocalObjectReference
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/httproute_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x.k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x.k8s.io_gateways.yaml
  config/crd/bases/networking.x.k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#110 Generates Deepcopy Funcs
  api/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#112 Updates and Includes Example Resources in Install
  Makefile
  examples/basic-http.yaml
  hack/install-examples.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#121 Update with video recording links
  docs-src/community.md
  docs/community/index.html
  docs/search/search_index.json
Labels: approved, cncf-cla: yes, size/M
