Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-04, with the labels that each got.

#145 Generates missing gatewayclasses CRD
  config/crd/bases/networking.x.k8s.io_gatewayclasses.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#128 Fix route selectors for the basic example
  examples/basic-http.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#133 Adding docs clarifying why TLS config is tied to Gateways
  docs-src/concepts.md
  docs/concepts/index.html
  docs/search/search_index.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#134 Updating calendar links to use official SIG-Network calendar
  docs-src/community.md
  docs/community/index.html
  docs/search/search_index.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#148 Change networking.x.k8s.io to networking.x-k8s.io
  PROJECT
  api/v1alpha1/gateway_types.go
  api/v1alpha1/generated.proto
  api/v1alpha1/groupversion_info.go
  config/crd/bases/networking.x.k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x.k8s.io_gateways.yaml
  config/crd/bases/networking.x.k8s.io_httproutes.yaml
  config/crd/bases/networking.x.k8s.io_tcproutes.yaml
  config/crd/bases/networking.x.k8s.io_trafficsplits.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_gatewayclasses.yaml
  config/crd/patches/cainjection_in_gateways.yaml
  config/crd/patches/cainjection_in_httproutes.yaml
  config/crd/patches/cainjection_in_tcproutes.yaml
  config/crd/patches/cainjection_in_trafficsplits.yaml
  config/crd/patches/webhook_in_gatewayclasses.yaml
  config/crd/patches/webhook_in_gateways.yaml
  config/crd/patches/webhook_in_httproutes.yaml
  config/crd/patches/webhook_in_tcproutes.yaml
  config/crd/patches/webhook_in_trafficsplits.yaml
  config/rbac/role.yaml
  config/samples/networking_v1alpha1_gateway.yaml
  config/samples/networking_v1alpha1_gatewayclass.yaml
  config/samples/networking_v1alpha1_httproute.yaml
  config/samples/networking_v1alpha1_tcproute.yaml
  config/samples/networking_v1alpha1_trafficsplit.yaml
  controllers/gateway_controller.go
  controllers/gatewayclass_controller.go
  controllers/httproute_controller.go
  controllers/tcproute_controller.go
  controllers/trafficsplit_controller.go
  examples/basic-http.yaml
  hack/delete-crds.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#146 Generates missing protos
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
Labels: approved, cncf-cla: yes, lgtm, size/L

#143 Copy edit the concepts page.
  docs-src/concepts.md
  docs/concepts/index.html
  docs/search/search_index.json
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#150 Fix lint error
  api/v1alpha1/gateway_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#154 fixec broken link for security model
  docs-src/concepts.md
  docs/concepts/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#155 Renames CRD artifacts missing from PR 148
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_trafficsplits.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#158 Add community info and purpose info to the README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#111 Delete RouteObjectReference; make group optional; add godoc
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/httproute_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#151 Adding CRD default for GatewayClass status
  api/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_trafficsplits.yaml
  examples/basic-http.yaml
  kubebuilder.mk
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#149 Adds CRD Verification
  Makefile
  hack/verify-crds.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#161 Updates Makefile and generates protos
  Makefile
  api/v1alpha1/generated.proto
Labels: approved, cncf-cla: yes, lgtm, size/XS

#140 Add Conditions for Listener name errors.
  api/v1alpha1/gateway_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
