Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-11, with the labels that each got.

#416 Updating Gateway hostname to more closely match HTTPRoute hostname
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs-src/tls.md
  docs/spec/index.html
  docs/tls/index.html
  examples/multiple-tcp.yaml
  examples/single-http.yaml
  examples/tls-basic.yaml
  examples/tls-cert-in-route.yaml
  examples/wildcard-http.yaml
  examples/wildcard-https.yaml
  examples/wildcard-tls-gateway.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#386 Update the FAQ.
  docs-src/concepts.md
  docs-src/faq.md
  docs/concepts/index.html
  docs/faq/index.html
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/L

#436 Cleanup from prealpha feedback
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/M

#444 Adding changelog for v0.1.0-rc2
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#421 define app-protocol annotation for k8s < 1.18
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  docs/tls/index.html
  examples/upstream-tls.yaml
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/M

#449 Various v1alpha1 API Clean-Up
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, priority/critical-urgent, size/L

#453 cleanup release.md
  docs-src/releases.md
  docs/releases/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#426 add shortName to Gateway and GatewayClass
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#456 Adding a reference in docs to Gatekeeper config example
  docs-src/security-model.md
  docs/security-model/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#458 add protocol and optional hostname to listener status
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#457 clarify HTTP Header name and value matching criteria
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#448 define HTTP route tiebreaker semantics
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#460 updated index page and created and images folder
  docs-src/images/api-model.png
  docs-src/index.md
  docs/images/api-model.png
  docs/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#466 Update GatewayClass Condition flow to add `Admitted` Condition type.
  apis/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#469 updated intro page image
  docs-src/images/api-model.png
  docs/images/api-model.png
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#468 Minor Intro Doc Improvements
  docs-src/index.md
  docs/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#471 fix GatewayClassStatus default value
  apis/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  docs-src/gatewayclass.md
  docs/gatewayclass/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#472 Fixing typo in changelog
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#473 Adding sig-network leads and service-apis maintainers as approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/M

#478 remove unnecessary Dockerfile
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#479 Updating Service APIs meeting times
  docs-src/community.md
  docs/community/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#484 Rename DroppedRoutes to DegradedRoutes in HTTPRoute
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#486 Update RouteSelector to Selector in Gateway
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
