Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-01, with the labels that each got.

#13 Update API with some stubs that match the sketch
  api/v1alpha1/gateway_types.go
  api/v1alpha1/httproute_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x.k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x.k8s.io_gateways.yaml
  config/crd/bases/networking.x.k8s.io_httproutes.yaml
  config/crd/bases/networking.x.k8s.io_tcproutes.yaml
  config/crd/bases/networking.x.k8s.io_trafficsplits.yaml
  controllers/gateway_controller.go
  controllers/gatewayclass_controller.go
  controllers/httproute_controller.go
  controllers/tcproute_controller.go
  controllers/trafficsplit_controller.go
  docs-src/devguide.md
  docs/devguide/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  examples/basic-http.yaml
  hack/delete-crds.sh
  main.go
Labels: approved, cncf-cla: yes, size/XXL

#6 Release cadence for Services/Ingress API
  docs-src/devguide.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#16 Removes whitespace introduced by commits b2c4093 and ff14200
  docs/devguide/index.html
  hack/delete-crds.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#25 Update schedule
  docs-src/community.md
  docs/community/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: approved, cncf-cla: yes, size/M

#27 Add make verify to docs.mk
  docs-src/.mkdocs-exclude
  docs.mk
Labels: approved, cncf-cla: yes, size/S

#28 Clean up mismatching autogen files
  api/v1alpha1/zz_generated.deepcopy.go
  docs/devguide/index.html
  docs/search/search_index.json
  docs/sitemap.xml.gz
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#24 Add verify-docs command
  docs-src/.mkdocs-exclude
  docs.mk
  hack/verify-docs.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#29 Use int32 instead of int for listener
  api/v1alpha1/gateway_types.go
  api/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#23 Updates dev docs and crd delete script
  Makefile
  docs-src/devguide.md
  docs/devguide/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  hack/delete-crds.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#39 Updates dev guide to use make install command
  docs-src/devguide.md
  docs/devguide/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: approved, cncf-cla: yes, lgtm, size/S

#38 Update autogenerated stuff that somehow was missed
  config/crd/bases/networking.x.k8s.io_gateways.yaml
  config/crd/bases/networking.x.k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#33 Bump golang version to 1.13.6
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#41 Update calendar links
  docs-src/community.md
  docs/community/index.html
  docs/search/search_index.json
  docs/sitemap.xml.gz
Labels: approved, cncf-cla: yes, size/M

#44 Adding official Zoom meetings
  docs-src/community.md
  docs/community/index.html
  docs/search/search_index.json
  docs/sitemap.xml.gz
Labels: approved, cncf-cla: yes, lgtm, size/M

#15 Fix GatewayClass scope
  api/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x.k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x.k8s.io_gateways.yaml
  config/crd/bases/networking.x.k8s.io_httproutes.yaml
  config/crd/bases/networking.x.k8s.io_tcproutes.yaml
  config/crd/bases/networking.x.k8s.io_trafficsplits.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#31 Reduce size of k8s.gcr.io/service-apis-mkdocs docker image
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
  mkdocs.dockerfile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#45 GatewayClass concepts
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x.k8s.io_gatewayclasses.yaml
  config/manager/kustomization.yaml
  docs-src/concepts.md
  docs/concepts/index.html
  docs/search/search_index.json
  docs/sitemap.xml
  docs/sitemap.xml.gz
Labels: approved, cncf-cla: yes, lgtm, size/XL
