Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-09, with the labels that each got.

#275 remove auto-generated controller from repo
  Makefile
  controllers/gateway_controller.go
  controllers/gatewayclass_controller.go
  controllers/httproute_controller.go
  controllers/suite_test.go
  controllers/tcproute_controller.go
  go.mod
  kubebuilder.mk
  main.go
  tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#283 Remove generated protobufs
  Makefile
  apis/v1alpha1/forwarding_target_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/generated.pb.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/local_object_reference_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsconfig_types.go
  go.mod
  go.sum
  hack/update-proto.sh
  hack/verify-proto.sh
  third_party/README.md
  third_party/protobuf/github.com/gogo/protobuf/gogoproto/gogo.proto
  third_party/protobuf/k8s.io/api/core/v1/generated.proto
  third_party/protobuf/k8s.io/apimachinery/pkg/api/resource/generated.proto
  third_party/protobuf/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto
  third_party/protobuf/k8s.io/apimachinery/pkg/runtime/generated.proto
  third_party/protobuf/k8s.io/apimachinery/pkg/runtime/schema/generated.proto
  third_party/protobuf/k8s.io/apimachinery/pkg/util/intstr/generated.proto
  third_party/protobuf/sigs.k8s.io/controller-runtime/pkg/scheme/generated.proto
  tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#284 Add back kustomize support
  config/crd/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#288 Fixes Install Make Target
  Makefile
  kubebuilder.mk
Labels: approved, cncf-cla: yes, lgtm, size/S

#299 Addding myself as a project owner
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#301 Fix code generation targets.
  Makefile
  hack/update-codegen.sh
  hack/verify-codegen.sh
  kubebuilder.mk
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#289 Make CertificateRefs field in TLSConfig optional instead of repeated.
  apis/v1alpha1/tlsconfig_types.go
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#300 Upgrade Go dependencies.
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#239 Add UDPRoute type for UDP support
  PROJECT
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  apis/v1alpha1/zz_generated.register.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/basic-udp.yaml
  pkg/client/clientset/versioned/typed/apis/v1alpha1/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_udproute.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/udproute.go
  pkg/client/informers/externalversions/apis/v1alpha1/interface.go
  pkg/client/informers/externalversions/apis/v1alpha1/udproute.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apis/v1alpha1/expansion_generated.go
  pkg/client/listers/apis/v1alpha1/udproute.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#282 tcproute: pluralize match and make action required
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#256 tls: introduce mode and sni to cert matching behavior
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/tlsconfig_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#280 httproute: rename filter and config Go types
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#294 Changing Gateway.Class to Gateway.GatewayClassName
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/basic-http.yaml
  examples/basic-tcp.yaml
  examples/default-match-http.yaml
  examples/http-trafficsplit.yaml
  examples/multiple-https.yaml
  examples/multiple-tcp.yaml
  examples/single-http.yaml
  examples/wildcard-http.yaml
  examples/wildcard-https.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#276 httproute: implement RequestMirror filter
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#305 Standardize common route status fields.
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#302 Standardize on the metav1.Condition type.
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/route_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#309 tls: make CertificateRef and Options optional
  apis/v1alpha1/tlsconfig_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#310 rename TLSConfig to GatewayTLSConfig
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/tlsconfig_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#314 move GatewayTLSConfig into gateway_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/tlsconfig_types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#277 implement TLSRoute for TLS support
  PROJECT
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  apis/v1alpha1/zz_generated.register.go
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/kustomization.yaml
  docs-src/spec.md
  docs/spec/index.html
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_tlsroute.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/tlsroute.go
  pkg/client/informers/externalversions/apis/v1alpha1/tlsroute.go
  pkg/client/listers/apis/v1alpha1/tlsroute.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#315 drop ClusterRole RBAC resource
  config/crd/kustomization.yaml
  config/rbac/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#316 add status subresource to UDPRoute
  apis/v1alpha1/udproute_types.go
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#318 use uppercase initialism for all XRoute
  apis/v1alpha1/forwarding_target_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/udproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#312 httproute: rename Action to Forward
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#319 use RouteStatus for TLSRoute
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#322 remove leftover protobuf tag in gateway
  apis/v1alpha1/gateway_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#321 udproute: pluralize match and remove protobuf tags
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#323 correct API group in package documentation
  apis/v1alpha1/doc.go
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#320 remove filters from TCP/TLS/UDP routes
  apis/v1alpha1/forwarding_target_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#308 Fixing default value for GatewayClass conditions
  apis/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#325 Sort gateway types in the order of introduction
  apis/v1alpha1/gateway_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#329 Unrevert client generation
  Makefile
  hack/update-codegen.sh
  pkg/client/clientset/versioned/typed/apis/v1alpha1/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/apis/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apis/v1alpha1/expansion_generated.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#328 Deprecate configmap as default on extension refs
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/local_object_reference_types.go
  apis/v1alpha1/route_extension_reference_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#327 Expands on GatewayClass.spec.controller
  docs-src/concepts.md
  docs/concepts/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#286 Updating ParametersRef docs and examples to be cluster-scoped
  apis/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/basic-http.yaml
  examples/basic-tcp.yaml
  examples/http-trafficsplit.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#338 Make HTTPRouteFilter types optional
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#340 Updates Introduction Docs
  docs-src/index.md
  docs/index.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#303 Adding Guidance for Conflict Resolution
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/concepts.md
  docs-src/spec.md
  docs/concepts/index.html
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#324 Update Gateway condition types.
  Makefile
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#263 Clarifying how AllowedGatewayNamespaces field should be interpreted
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  docs-src/security-model.md
  docs-src/spec.md
  docs/security-model/index.html
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#281 tls: configure downstream TLS certificate in Routes
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/tls-in-route.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#285 Adding Gateway selection to Routes
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/security-model.md
  docs-src/spec.md
  docs/security-model/index.html
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#268 Adding BackendPolicy for Service-level config
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  apis/v1alpha1/zz_generated.register.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  docs-src/concepts.md
  docs-src/spec.md
  docs/concepts/index.html
  docs/spec/index.html
  examples/backendpolicy.yaml
  pkg/client/clientset/versioned/typed/apis/v1alpha1/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/backendpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_backendpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/apis/v1alpha1/backendpolicy.go
  pkg/client/informers/externalversions/apis/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apis/v1alpha1/backendpolicy.go
  pkg/client/listers/apis/v1alpha1/expansion_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#347 GatewayClass: Add omitempty to provisionedGateways
  apis/v1alpha1/gatewayclass_types.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#350 Remove git conflict log in security-model.md
  docs-src/security-model.md
  docs/security-model/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#353 Flattening Routes
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/route_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/basic-http.yaml
  examples/basic-tcp.yaml
  examples/basic-udp.yaml
  examples/default-match-http.yaml
  examples/http-trafficsplit.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL
