Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-06, with the labels that each got.

#182 Mark Gateway status fields optional
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/generated.proto
  config/crd/bases/networking.x-k8s.io_gateways.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#192 Singularizes example HTTPRoute hostname
  examples/basic-http.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#191 Concepts doc minor fixes and updates
  docs-src/concepts.md
  docs/concepts/index.html
  docs/search/search_index.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#207 Document root CRD objects as API resource types.
  api/v1alpha1/gateway_types.go
  api/v1alpha1/httproute_types.go
  api/v1alpha1/tcproute_types.go
  api/v1alpha1/trafficsplit_types.go
  docs-src/spec.md
  docs/search/search_index.json
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#193 Rewrite Listeners in terms of an endpoint concept.
  api/v1alpha1/gateway_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/search/search_index.json
  docs/spec/index.html
  examples/basic-http.yaml
  examples/multiple-https.yaml
  examples/multiple-tcp.yaml
  examples/single-http.yaml
  examples/wildcard-http.yaml
  examples/wildcard-https.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#208 Remove search from docs, fix apidocs generation
  Makefile
  docs/404.html
  docs/community/index.html
  docs/concepts/index.html
  docs/cookbook/index.html
  docs/devguide/index.html
  docs/enhancement-requests/index.html
  docs/faq/index.html
  docs/feedback/index.html
  docs/index.html
  docs/releases/index.html
  docs/search/search_index.json
  docs/security-model/index.html
  docs/spec/index.html
  docs/userguide/index.html
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#194 Adding new status conditions covering forbidden namespaces
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/generated.proto
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#211 Update root object tags for API documentation.
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/httproute_types.go
  api/v1alpha1/tcproute_types.go
  api/v1alpha1/trafficsplit_types.go
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#212 Align Conditions with KEP-1623.
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#169 clarify matching behavior for HTTP Headers
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/httproute_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#209 Describe core, extended, custom support levels
  docs-src/concepts.md
  docs/concepts/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#214 httproute: pluralize hostname and allow for wildcards
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/httproute_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#215 Bump dependencies
  api/v1alpha1/generated.pb.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_trafficsplits.yaml
  controllers/suite_test.go
  go.mod
  go.sum
  third_party/protobuf/k8s.io/api/core/v1/generated.proto
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#198 Adding RouteNamespaces for Gateway and GatewayClass
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/samples/networking_v1alpha1_gateway.yaml
  config/samples/networking_v1alpha1_gatewayclass.yaml
  docs-src/security-model.md
  docs-src/spec.md
  docs/security-model/index.html
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XXL
