Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-05, with the labels that each got.

#172 Consolidate tooling imports.
  build/tools.go
  tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#165 Adds a GitHub Issues template for reporting bugs
  .github/ISSUE_TEMPLATE/bug.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#171 Make Gateway.Status a subresource
  api/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#167 Decouples the ListenerTLS API type from Listener
  api/v1alpha1/gateway_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/tlsconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#166 Makefile improvements
  Makefile
  docs-src/devguide.md
  docs/devguide/index.html
  docs/search/search_index.json
  hack/verify-crds.sh
  hack/verify-proto.sh
  kubebuilder.mk
Labels: approved, cncf-cla: yes, lgtm, size/L

#181 Fix Listener protocol constant spellings.
  api/v1alpha1/gateway_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#168 Mark fields in Condition required
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#187 Fix issue with generated zz_deepcopy code
  api/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#163 Refactors LocalObjectReference API type
  api/v1alpha1/gateway_types.go
  api/v1alpha1/gatewayclass_types.go
  api/v1alpha1/generated.pb.go
  api/v1alpha1/generated.proto
  api/v1alpha1/httproute_types.go
  api/v1alpha1/local_object_reference_types.go
  api/v1alpha1/tlsconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  examples/basic-http.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL
