Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-08, with the labels that each got.

#242 httproute: correct conformance for regex support
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#250 Pluralizes forwardTo field of TCPRoute
  apis/v1alpha1/forwarding_target_types.go
  apis/v1alpha1/generated.pb.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
  examples/basic-tcp.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#251 Reorders make all targets
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#260 Update default PathMatchType in HTTPRoute to be prefix.
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#261 Fix typo in httproute_types.go.
  apis/v1alpha1/httproute_types.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#257 tls: drop tls.MinimumVersion in favor of tls.Options
  apis/v1alpha1/generated.pb.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/tlsconfig_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#258 httproute: drop default HTTPRouteHost
  apis/v1alpha1/generated.pb.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#241 httproute: pluralize matches for multiple matches in a single rule
  apis/v1alpha1/generated.pb.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#252 Update validation rules.
  apis/v1alpha1/forwarding_target_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/generated.pb.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#266 fix typos
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#278 add missing status subresource
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#274 remove unnecessary YAML files from the repo
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_gatewayclasses.yaml
  config/crd/patches/cainjection_in_gateways.yaml
  config/crd/patches/cainjection_in_httproutes.yaml
  config/crd/patches/cainjection_in_tcproutes.yaml
  config/crd/patches/webhook_in_gatewayclasses.yaml
  config/crd/patches/webhook_in_gateways.yaml
  config/crd/patches/webhook_in_httproutes.yaml
  config/crd/patches/webhook_in_tcproutes.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_prometheus_metrics_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/samples/networking_v1alpha1_gateway.yaml
  config/samples/networking_v1alpha1_gatewayclass.yaml
  config/samples/networking_v1alpha1_httproute.yaml
  config/samples/networking_v1alpha1_tcproute.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#86 HTTPRoute, TCPRoute: Add gateway status information
  apis/v1alpha1/generated.pb.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#249 httproute: implement HTTPRouteFilter
  apis/v1alpha1/forwarding_target_types.go
  apis/v1alpha1/generated.pb.go
  apis/v1alpha1/generated.proto
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#279 Add linguist attribute to generated files.
  .gitattributes
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
