Repository kubernetes-sigs/gateway-api, pull requests merged in 2020-12, with the labels that each got.

#485 Replace obsolete status ConditionInvalidRoutes with InvalidRoutesRef
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#474 Adding a PR Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#483 Fixing bad link in README.md
  README.md
  docs-src/api-overview.md
  docs-src/security-model.md
  docs/api-overview/index.html
  docs/security-model/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#374 document NamedAddress
  apis/v1alpha1/gateway_types.go
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#490 move all images into images/ directory
  docs-src/api-overview.md
  docs-src/httproute.md
  docs-src/images/httproute-basic-example.svg
  docs-src/images/schema-uml.svg
  docs-src/images/single-service-gateway.png
  docs-src/images/tls-overview.svg
  docs-src/simple-gateway.md
  docs-src/tls.md
  docs/api-overview/index.html
  docs/httproute/index.html
  docs/images/httproute-basic-example.svg
  docs/images/schema-uml.svg
  docs/images/single-service-gateway.png
  docs/images/tls-overview.svg
  docs/simple-gateway/index.html
  docs/tls/index.html
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#494 Fix broken doc link
  docs-src/faq.md
  docs/faq/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#495 remove bowei from owners file
  OWNERS
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#497 fix broken link in FAQ doc
  docs-src/faq.md
  docs/faq/index.html
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#493 Increasing max length of ForwardTo from 4 to 16
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#492 Clarifying approach to versioning
  RELEASE.md
  docs-src/releases.md
  docs/releases/index.html
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#499 examples: Remove namespace from examples
  docs/multiple-ns/index.html
  examples/basic-tcp.yaml
  examples/basic-udp.yaml
  examples/default-match-http.yaml
  examples/multiple-tcp.yaml
  examples/routes-in-multiple-namespaces.yaml
  examples/single-http.yaml
  examples/wildcard-http.yaml
  examples/wildcard-https.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, ok-to-test, size/S

#501 Clarifying that unreleased changes may be reverted
  docs-src/releases.md
  docs/releases/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#504 docs: pin to CRD manifests to v0.1.0
  docs-src/getting-started.md
  docs/getting-started/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#503 Document values for named constants.
  docs-src/spec.md
  docs/spec/index.html
  go.mod
  go.sum
  hack/api-docs/type.tpl
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#475 Add Set field to HTTPRequestHeaderFilter
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#508 build: Run go test from Make
  Makefile
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XS

#512 Cleaning up links to meeting notes and recordings
  docs-src/community.md
  docs/community/index.html
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L
