Repository kubernetes-sigs/gateway-api, pull requests merged in 2021-01, with the labels that each got.

#526 disable verbose logging for verify target
  Makefile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#527 indented api-overview.md to 80 chars
  docs-src/api-overview.md
  docs/api-overview/index.html
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#511 Switch to golangci-lint.
  .golangci.yml
  hack/verify-gofmt.sh
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#513 Revert documention generator fork.
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#533 bump go deps to latest version
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#534 Add link to "Kubernetes API Versioning" by using correct name
  docs-src/releases.md
  docs/releases/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#514 More detailed and holistic documentation for Gateway<->Route binding
  docs-src/api-overview.md
  docs-src/images/gateway-route-binding.png
  docs/api-overview/index.html
  docs/images/gateway-route-binding.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/L

#518 Fixes TLS Mode Defaulting
  apis/v1alpha1/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S
