Repository kubernetes-sigs/gateway-api, pull requests merged in 2021-09, with the labels that each got.

#845 Fix markdown list formatting.
  apis/v1alpha2/gateway_types.go
  config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
Labels: size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#843 Add APISIX implementation
  site-src/implementations.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#844 docs: add ssl passthrough note in FAQ
  apis/v1alpha2/gateway_types.go
  site-src/faq.md
Labels: approved, size/S, tide/merge-method-squash, kind/documentation, cncf-cla: yes, lgtm

#850 httproute: drop ImplementationSpecific match types
  apis/v1alpha2/httproute_types.go
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
Labels: kind/api-change, approved, size/M, cncf-cla: yes, lgtm, breaking-change

#839 Another round of v1alpha2 cleanup
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/referencepolicy_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/tcproute_types.go
  apis/v1alpha2/tlsroute_types.go
  apis/v1alpha2/udproute_types.go
  apis/v1alpha2/validation/gatewayclass.go
  apis/v1alpha2/validation/gatewayclass_test.go
  config/crd/v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_udproutes.yaml
  examples/v1alpha2/basic-http.yaml
  examples/v1alpha2/default-match-http.yaml
  examples/v1alpha2/http-redirect.yaml
  hack/invalid-examples/v1alpha2/gatewayclass/invalid-controller.yaml
  pkg/admission/server_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#853 docs: Use v0.4.0-rc1 in "Getting started with Gateway APIs" for v1alpha2
  site-src/v1alpha2/guides/getting-started.md
Labels: ok-to-test, size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#857 Adding missing references pages to docs navigation
  mkdocs.yml
  site-src/v1alpha2/references/cross-namespace-references.md
  site-src/v1alpha2/references/policy-attachment.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#858 Fixing broken link to spec page
  README.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#859 Clarifying how HTTP and TLS Route status should be populated
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/tlsroute_types.go
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#807 docs: update multiple-ns guide for v1alpha2
  examples/v1alpha2/cross-namespace-routing/0-namespaces.yaml
  examples/v1alpha2/cross-namespace-routing/gateway.yaml
  examples/v1alpha2/cross-namespace-routing/site-route.yaml
  examples/v1alpha2/cross-namespace-routing/store-route.yaml
  site-src/v1alpha2/guides/multiple-ns.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#864 Merging v1alpha2 concepts docs into unversioned docs
  site-src/concepts/guidelines.md
  site-src/concepts/security-model.md
  site-src/v1alpha2/concepts/api-overview.md
  site-src/v1alpha2/concepts/guidelines.md
  site-src/v1alpha2/concepts/security-model.md
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm, size/XL

#865 Route cleanup for v1alpha2 sig-network review
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/object_reference_types.go
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_udproutes.yaml
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#863 multiple fixes to HTTPRequestRedirect filter
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
  examples/v1alpha2/http-redirect.yaml
Labels: kind/api-change, approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#870 Adding guidance on Kind vs. Resource in implementation guidelines
  site-src/concepts/guidelines.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#856 Adding GEP 851: Allow Multiple Certificate Refs per Gateway Listener
  site-src/geps/gep-851.md
Labels: approved, size/M, cncf-cla: yes, lgtm, kind/gep

#869 Align path prefix matching with Ingress.
  apis/v1alpha2/httproute_types.go
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
Labels: kind/bug, kind/api-change, approved, size/M, cncf-cla: yes, lgtm

#875 Fix HTTP path match documentation.
  apis/v1alpha2/httproute_types.go
Labels: kind/bug, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#872 Remove duplicate validation from CRD & Webhook
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/gateway_test.go
  pkg/admission/server_test.go
Labels: ok-to-test, approved, tide/merge-method-squash, kind/cleanup, cncf-cla: yes, lgtm, size/L

#879 Clarifying that HTTP listeners may be used for Cleartext HTTP/2
  apis/v1alpha2/gateway_types.go
Labels: kind/feature, size/XS, approved, cncf-cla: yes, lgtm

#878 Clarifying the fields that all Route types must include
  apis/v1alpha2/shared_types.go
  site-src/concepts/api-overview.md
Labels: approved, size/S, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#852 feat: support to configure multiple certificates on GatewayTLSConfig
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
  examples/v1alpha2/cross-namespace-routing/gateway.yaml
  examples/v1alpha2/tls-basic.yaml
  examples/v1alpha2/tls-cert-cross-namespace.yaml
  examples/v1alpha2/wildcard-tls-gateway.yaml
Labels: kind/feature, ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#883 v1alpha2 validation fix/update
  .golangci.yml
  apis/v1alpha1/validation/validation_test.go
  apis/v1alpha2/validation/gatewayclass_test.go
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/httproute_test.go
  pkg/util/utils.go
  pkg/util/utils_test.go
Labels: kind/bug, ok-to-test, approved, tide/merge-method-squash, kind/cleanup, cncf-cla: yes, lgtm, size/XL

#842 Add protocol specific validation for Gateway api
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/gateway_test.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#882 Removing scope fields from object references
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_udproutes.yaml
Labels: kind/api-change, approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#885 Fix incorrect urls
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/gatewayclass.go
  apis/v1alpha2/validation/httproute.go
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#880 Reworking Policy vs. Filter Documentation
  site-src/v1alpha2/references/policy-attachment.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#871 Add validation for Kubernetes object name fields and ProtocolType
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/object_reference_types.go
  apis/v1alpha2/policy_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/validation/httproute_test.go
  config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_udproutes.yaml
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#886 Adding TLS options validation as final sig-network review follow up
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
Labels: kind/api-change, approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#888 Corrected broken getting started
  README.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#889 remove outdated version label
  deploy/certificate_config.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm
