Repository kubernetes-sigs/gateway-api, pull requests merged in 2021-06, with the labels that each got.

#688 Clarify direction for backend weights
  apis/v1alpha2/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#674 Update documentation around hostnames for HTTPRoute and Listener
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/shared_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/M

#686 use squash as default merge behavior
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash

#692 Add HAProxy Ingress as a downstream implementation
  site-src/references/implementations.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#693 Revert PR template labels
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#694 Updating v1alpha2 guidelines docs to match v1alpha1
  site-src/concepts/guidelines.md
  site-src/v1alpha2/concepts/guidelines.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#672 Adding hostname address type
  apis/v1alpha2/gateway_types.go
  config/crd/bases/networking.x-k8s.io_gateways.yaml
Labels: approved, cncf-cla: yes, kind/api-change, kind/feature, lgtm, size/S

#682 tlsroute: make TLSRoute structure consistent with HTTPRoute
  apis/v1alpha2/tlsroute_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
Labels: approved, breaking-change, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, size/M

#697 Fix doc as user cannot omit port field in Gateway
  site-src/concepts/api-overview.md
  site-src/v1alpha2/concepts/api-overview.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, ok-to-test, size/XS

#698 updated implementations page for GKE gateway controller
  site-src/references/implementations.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/S

#700 recursively install examples
  hack/install-examples.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS
