Repository kubernetes-sigs/gateway-api, pull requests merged in 2021-02, with the labels that each got.

#540 Cleaning up codegen
  Makefile
  apis/v1alpha1/gatewayclass_types.go
  hack/update-codegen.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#538 Aligns API Fields with K8s Conventions
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/local_object_reference_types.go
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/guidelines.md
  docs-src/spec.md
  docs/guidelines/index.html
  docs/spec/index.html
Labels: approved, cncf-cla: yes, kind/api-change, kind/bug, lgtm, size/L

#528 Updates RouteStatus Godocs
  apis/v1alpha1/shared_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, size/S

#546 Fixes Typo in HTTPRoute Godocs
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#543 allow namespace-scoped parametersRef
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/local_object_reference_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  docs-src/spec.md
  docs/spec/index.html
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/M

#550 updated personas on main page
  docs-src/images/api-model.png
  docs/images/api-model.png
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#551 updated personas on main page
  docs-src/images/api-model.png
  docs/images/api-model.png
Labels: cncf-cla: yes, kind/documentation, needs-ok-to-test, size/XS

#552 Make an editorial pass over the API documentation.
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  docs-src/spec.html
  docs/spec.html
  docs/spec/index.html
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XXL

#553 Adding notes referring to previous project name
  README.md
  docs-src/index.md
  docs/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#548 docs: add changelog for v0.2.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#557 bump up references to v0.2.0
  docs-src/getting-started.md
  docs/getting-started/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#555 docs: Rename Services API to Gateway API in Getting Started
  docs-src/getting-started.md
  docs/getting-started/index.html
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#560 Adding Netlify support (Part 1)
  .gitattributes
  .gitignore
  Makefile
  docs-src/devguide.md
  docs.mk
  docs/devguide/index.html
  docs/genspec.html
  docs/spec.html
  hack/verify-apidocs.sh
  hack/verify-docs.sh
  mkdocs.dockerfile
  netlify.toml
  requirements.txt
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XXL
