Repository kubernetes-sigs/gateway-api, pull requests merged in 2021-11, with the labels that each got.

#924 Fix link to the implementations page
  site-src/v1alpha1/guides/getting-started.md
  site-src/v1alpha2/guides/getting-started.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#918 Add GEP-917 to document conformance principles
  site-src/geps/gep-917.md
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/gep

#900 Clarifying PathPrefix matching
  apis/v1alpha2/httproute_types.go
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#929 bump go.mod to 1.17
  go.mod
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#923 Adding GEP 922: Gateway API Versioning Plan
  site-src/geps/gep-922.md
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/gep

#931 Use correct namespace for the example of cross namespace certificate references
  examples/v1alpha2/tls-cert-cross-namespace.yaml
Labels: kind/bug, ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#936 Replace networking.x-k8s.io with gateway.networking.k8s.io in hack/delete-crds.sh
  hack/delete-crds.sh
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#731 Adding GEP 726: Path Rewrites and Redirects
  site-src/geps/gep-726.md
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/gep

#943 Fix site implementations typo
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#940 Fixing make docs sed to work on BSD and Linux
  Makefile
  hack/make-docs.sh
Labels: kind/bug, ok-to-test, approved, tide/merge-method-squash, size/M, cncf-cla: yes, lgtm

#944 Validate that Service backend refs have a port.
  Makefile
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/httproute_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/L

#948 updated link for contributor-cheatsheet
  CONTRIBUTING.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#937 Adding details to Conformance GEP
  site-src/geps/gep-917.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm, kind/gep

#950 images: use k8s-staging-test-infra/gcb-docker-gcloud
  cloudbuild.yaml
Labels: size/XS, approved, cncf-cla: yes, lgtm
