Repository kubernetes-sigs/gateway-api, pull requests merged in 2021-07, with the labels that each got.

#684 Add proposal for GEPs
  .github/ISSUE_TEMPLATE/enhancement.md
  site-src/contributing/enhancement-requests.md
  site-src/contributing/gep.md
  site-src/geps/gep-696.md
  site-src/v1alpha2/contributing/enhancement-requests.md
Labels: approved, cncf-cla: yes, kind/design, kind/feature, lgtm, size/L, tide/merge-method-squash

#703 Fix broken links
  mkdocs.yml
  site-src/contributing/enhancement-requests.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#683 httproute: introduce RequestRedirect filter
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  examples/v1alpha2/http-redirect.yaml
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#704 use camelCase and not snake_case
  apis/v1alpha2/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#701 Justify text on the website.
  mkdocs.yml
  site-src/css/extra.css
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#706 Adding symlinks to avoid unnecessary duplication in v1alpha2 docs
  site-src/contributing
  site-src/contributing/community.md
  site-src/contributing/devguide.md
  site-src/contributing/enhancement-requests.md
  site-src/faq.md
  site-src/index.md
  site-src/references/implementations.md
  site-src/references/releases.md
  site-src/v1alpha2/contributing/gep.md
  site-src/v1alpha2/faq.md
  site-src/v1alpha2/references/implementations.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/XL

#710 Updating meeting times
  site-src/v1alpha2/contributing/community.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/S

#702 Add a virtualenv convenience target for mkdocs.
  Makefile
  hack/boilerplate/boilerplate.py
  site-src/v1alpha2/contributing/devguide.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#712 Updating GEP 696 to consistently reference newer issue
  site-src/geps/gep-696.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#717 gitignore: add .venv/
  .gitignore
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#720 add kind gep in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#721 fix support level for HTTPRequestHeaderFilter
  apis/v1alpha2/httproute_types.go
  config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#711 Adding GEP-709: Cross namespace references from Routes
  site-src/geps/gep-709.md
  site-src/geps/images/709-inline.png
  site-src/geps/images/709-referencepolicy.png
Labels: approved, cncf-cla: yes, kind/gep, lgtm, size/L

#723 Clarifying Redirect Support levels
  apis/v1alpha2/httproute_types.go
  config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
  site-src/v1alpha2/concepts/guidelines.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/S

#728 Fixing wording in enhancement template
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#715 Adding GEP-713: Policy Attachment
  site-src/geps/gep-713.md
  site-src/geps/images/713-hierarchy.png
  site-src/geps/images/713-ingress-attachment.png
  site-src/geps/images/713-ingress-complex.png
  site-src/geps/images/713-ingress-simple.png
  site-src/geps/images/713-mesh-complex.png
  site-src/geps/images/713-mesh-simple.png
  site-src/geps/images/713-policy-hierarchy.png
  site-src/geps/images/713-servicebinding-complex.png
  site-src/geps/images/713-servicebinding-simple.png
Labels: approved, cncf-cla: yes, kind/gep, lgtm, size/XL, tide/merge-method-squash

#722 Tweaks to ReferencePolicy GEP
  mkdocs.yml
  site-src/geps/gep-709.md
Labels: approved, cncf-cla: yes, kind/gep, lgtm, size/M

#729 Adding suggested reasons for when conditions are healthy
  apis/v1alpha1/shared_types.go
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/gatewayclass_types.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#734 Adding Nick as a project maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#562 Allow empty string for Group field to indicate core API group
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/local_object_reference_types.go
  config/crd/bases/gateway.networking.k8s.io_backendpolicies.yaml
  config/crd/bases/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/bases/gateway.networking.k8s.io_gateways.yaml
  config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
  config/crd/bases/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/bases/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/bases/gateway.networking.k8s.io_udproutes.yaml
  site-src/v1alpha2/guides/tls.md
Labels: approved, cncf-cla: yes, kind/api-change, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#732 Removing BackendPolicy
  apis/v1alpha2/backendpolicy_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  apis/v1alpha2/zz_generated.register.go
  config/crd/bases/gateway.networking.k8s.io_backendpolicies.yaml
  config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
  config/crd/bases/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/bases/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/bases/gateway.networking.k8s.io_udproutes.yaml
  pkg/client/clientset/gateway/versioned/typed/apis/v1alpha2/apis_client.go
  pkg/client/clientset/gateway/versioned/typed/apis/v1alpha2/backendpolicy.go
  pkg/client/clientset/gateway/versioned/typed/apis/v1alpha2/fake/fake_apis_client.go
  pkg/client/clientset/gateway/versioned/typed/apis/v1alpha2/fake/fake_backendpolicy.go
  pkg/client/clientset/gateway/versioned/typed/apis/v1alpha2/generated_expansion.go
  pkg/client/informers/gateway/externalversions/apis/v1alpha2/backendpolicy.go
  pkg/client/informers/gateway/externalversions/apis/v1alpha2/interface.go
  pkg/client/informers/gateway/externalversions/generic.go
  pkg/client/listers/gateway/apis/v1alpha2/backendpolicy.go
  pkg/client/listers/gateway/apis/v1alpha2/expansion_generated.go
  site-src/v1alpha2/concepts/api-overview.md
  site-src/v1alpha2/faq.md
  site-src/v1alpha2/guides/tls.md
Labels: approved, breaking-change, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, size/L
