Repository kubernetes-sigs/gateway-api, pull requests merged in 2021-04, with the labels that each got.

#600 You changed the link, so so did we 🙂
  site-src/implementations.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#597 Introduces a Validation Package
  apis/v1alpha1/validation/doc.go
  apis/v1alpha1/validation/validation.go
  apis/v1alpha1/validation/validation_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#592 Adding gateway-api category and age column to CRDs
  apis/v1alpha1/backendpolicy_types.go
  apis/v1alpha1/gateway_types.go
  apis/v1alpha1/gatewayclass_types.go
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#605 Bump up dependencies to k8s v1.21
  config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
  config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
  config/crd/bases/networking.x-k8s.io_gateways.yaml
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#601 Adding structure to site-src to match site structure
  Makefile
  README.md
  RELEASE.md
  mkdocs.yml
  site-src/api-types/gateway.md
  site-src/api-types/gatewayclass.md
  site-src/api-types/httproute.md
  site-src/concepts/api-overview.md
  site-src/concepts/guidelines.md
  site-src/concepts/security-model.md
  site-src/contributing/community.md
  site-src/contributing/devguide.md
  site-src/contributing/enhancement-requests.md
  site-src/faq.md
  site-src/guides/getting-started.md
  site-src/guides/http-routing.md
  site-src/guides/index.md
  site-src/guides/multiple-ns.md
  site-src/guides/simple-gateway.md
  site-src/guides/tcp.md
  site-src/guides/tls.md
  site-src/guides/traffic-splitting.md
  site-src/index.md
  site-src/references/implementations.md
  site-src/references/releases.md
  site-src/references/spec.md
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/L

#609 fix broken links after site structure change
  site-src/concepts/api-overview.md
  site-src/faq.md
  site-src/guides/getting-started.md
  site-src/guides/http-routing.md
  site-src/guides/tcp.md
  site-src/guides/traffic-splitting.md
  site-src/index.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#608 fix broken link to IngressClass KEP
  site-src/api-types/gatewayclass.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#606 httproute: add duplicate filter validation
  apis/v1alpha1/validation/validation.go
  apis/v1alpha1/validation/validation_test.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#585 getting-started.md page refresh
  README.md
  mkdocs.yml
  site-src/guides/getting-started.md
  site-src/guides/index.md
  site-src/index.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#618 fix broken link to implementations page from getting-started page
  site-src/guides/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#619 remove file links and use only URL links throughout the docs site
  site-src/guides/getting-started.md
  site-src/guides/traffic-splitting.md
  site-src/index.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#617 implement an admission webhook server
  .gitignore
  Dockerfile
  cmd/admission/main.go
  deploy/admission_webhook.yaml
  deploy/certificate_config.yaml
  go.mod
  go.sum
  pkg/admission/server.go
  pkg/admission/server_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#620 Adding conflict resolution guidance for equivalent rules within a route
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/XS

#621 automate webhook server image build and publishing
  Dockerfile
  Makefile
  cloudbuild.yaml
  cmd/admission/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#628 Fix typo in FAQ doc
  site-src/concepts/api-overview.md
  site-src/faq.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS

#616 Adding a controller field to GatewayReference in RouteGatewayStatus
  apis/v1alpha1/shared_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
Labels: approved, cncf-cla: yes, kind/api-change, kind/cleanup, lgtm, size/M

#632 Fix typo
  site-src/concepts/api-overview.md
  site-src/guides/getting-started.md
  site-src/guides/traffic-splitting.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#631 Adding QueryParam matching to HTTPRoute
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  examples/basic-http.yaml
Labels: approved, cncf-cla: yes, kind/api-change, kind/feature, lgtm, size/M

#635 Deprecating NoSuchGatewayClass status reason
  apis/v1alpha1/gateway_types.go
Labels: approved, cncf-cla: yes, kind/cleanup, kind/deprecation, lgtm, size/S

#626 Clarifying how conflicting matches should be resolved in non-HTTP Routes
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
  config/crd/bases/networking.x-k8s.io_tcproutes.yaml
  config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
  config/crd/bases/networking.x-k8s.io_udproutes.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, kind/documentation, lgtm, size/L

#636 Cleaning up query param matching spec
  apis/v1alpha1/httproute_types.go
  config/crd/bases/networking.x-k8s.io_httproutes.yaml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#639 Add note about "implementation-specific" vs conformance levels
  site-src/concepts/guidelines.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#633 Enhance docs around Gateways, Routes and TLS
  site-src/guides/tls.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#641 Adding Changelog for v0.3.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#643 Fixup the getting-started guide to use the v0.3.0 release.
  site-src/guides/getting-started.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, ok-to-test, size/XS
