Repository kubernetes-sigs/gateway-api, pull requests merged in 2021-12, with the labels that each got.

#951 Fixing BackendRef docs for ResolvedRefs condition
  apis/v1alpha2/httproute_types.go
Labels: kind/bug, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#945 Implementing GEPs 726 and 922: Rewrites + Experimental CRDs
  .gitattributes
  apis/v1alpha2/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/stable/gateway.networking.k8s.io_gateways.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/verify-examples-kind.sh
  pkg/generator/main.go
Labels: kind/feature, approved, size/XXL, cncf-cla: yes, lgtm

#952 fix: kustomize resource paths
  config/crd/kustomization.yaml
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm, kind/regression

#953 Fix ReferencePolicy docs about empty value in `spec.to.name`
  apis/v1alpha2/referencepolicy_types.go
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/stable/gateway.networking.k8s.io_referencepolicies.yaml
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#954 Fix broken site links
  site-src/faq.md
  site-src/geps/gep-724.md
  site-src/v1alpha1/api-types/httproute.md
  site-src/v1alpha1/guides/http-routing.md
  site-src/v1alpha1/guides/multiple-ns.md
  site-src/v1alpha2/api-types/httproute.md
  site-src/v1alpha2/guides/multiple-ns.md
  site-src/v1alpha2/guides/tcp.md
  site-src/v1alpha2/references/cross-namespace-references.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#932 GEP 735 L4 Traffic Matching
  site-src/geps/gep-735.md
Labels: kind/feature, kind/design, kind/api-change, approved, cncf-cla: yes, lgtm, size/L, kind/gep

#961 Update version of golangci-lint as well as remove deprecated linters.
  .golangci.yml
  hack/verify-golint.sh
  pkg/util/utils_test.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#959 hack: fixup deepcopy-gen for CRDs
  apis/v1alpha2/zz_generated.deepcopy.go
  hack/update-codegen.sh
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#967 Cherrypick #909 and #964 into release-0.4
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/referencepolicy_types.go
  config/crd/v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/v1alpha2/gateway.networking.k8s.io_referencepolicies.yaml
  hack/invalid-examples/v1alpha2/referencepolicy/missing-ns.yaml
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#946 Validating HTTPRouteFilter type consistency
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/httproute_test.go
Labels: kind/feature, ok-to-test, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/L

#971 Add missing word in Introduction
  site-src/v1alpha2/references/cross-namespace-references.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#970 Fix HTTPRoute validation tests.
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/httproute_test.go
  pkg/admission/server_test.go
Labels: kind/bug, approved, size/XXL, kind/cleanup, cncf-cla: yes, lgtm

#975 Fix Grammar
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, cncf-cla: yes, lgtm
