Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-11, with the labels that each got.

#1470 Webhook: validate TLS config must be set when protocol is HTTPS or TLS.
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/gateway_test.go
  apis/v1beta1/validation/gateway.go
  apis/v1beta1/validation/gateway_test.go
Labels: kind/feature, ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1501 Fix invalid HTTPS listeners in example resources
  examples/experimental/basic-grpc.yaml
  examples/experimental/v1alpha2/grpc-routing/gateway.yaml
  examples/standard/http-redirect.yaml
Labels: approved, size/S, kind/failing-test, kind/cleanup, cncf-cla: yes, lgtm

#1490 Webhook: validate at least one of GRPCRoute.Rules.Matches.{Method,Service} is supplied
  apis/v1alpha2/validation/grpcroute.go
  apis/v1alpha2/validation/grpcroute_test.go
  pkg/admission/server.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#1504 Updates Envoy Gateway Implementation Details
  site-src/implementations.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1502 docs: mark GEP-735 as declined
  mkdocs.yml
  site-src/geps/gep-735.md
Labels: approved, size/S, cncf-cla: yes, lgtm, kind/gep

#1505 Make Istio impl as "beta"
  site-src/implementations.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1476 conformance: all cases for which a TLS secret can be invalid are tested
  conformance/tests/gateway-invalid-tls-certificateref.go
  conformance/tests/gateway-invalid-tls-certificateref.yaml
  conformance/tests/gateway-secret-missing-referenced-secret.go
  conformance/tests/gateway-secret-missing-referenced-secret.yaml
  conformance/utils/suite/suite.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1506 Improve GRPCRoute Go Structs
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
Labels: kind/bug, approved, size/S, needs-ok-to-test, cncf-cla: yes, lgtm

#1513 Fix Broken Links in Docs Causing Rendering Failures
  examples/standard/reference-grant.yaml
  site-src/blog/2021/introducing-v1alpha2.md
  site-src/concepts/security-model.md
  site-src/guides/tls.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1518 apis: update Group default docs and examples for *Reference types
  apis/v1beta1/object_reference_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1497 Add and test single filter action per header restriction
  apis/v1beta1/httproute_types.go
  apis/v1beta1/validation/httproute.go
  apis/v1beta1/validation/httproute_test.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: ok-to-test, approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1462 Add Docker image support multi OS archs
  Dockerfile
  README.md
  hack/build-and-push.sh
Labels: kind/feature, ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1520 conformance: Fix logic in HTTPRouteResponseHeaderModifier test
  conformance/base/manifests.yaml
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-exact-path-matching.go
  conformance/tests/httproute-header-matching.go
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-invalid-backendref-nonexistent.go
  conformance/tests/httproute-invalid-backendref-unknown-kind.go
  conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
  conformance/tests/httproute-invalid-reference-grant.go
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-method-matching.go
  conformance/tests/httproute-query-param-matching.go
  conformance/tests/httproute-reference-grant.go
  conformance/tests/httproute-request-header-modifier.go
  conformance/tests/httproute-response-header-modifier.go
  conformance/tests/httproute-response-header-modifier.yaml
  conformance/tests/httproute-simple-same-namespace.go
  conformance/utils/http/http.go
Labels: kind/bug, ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1524 conformance: fix invalid `for` loop in InvalidTls test
  conformance/tests/gateway-invalid-tls-certificateref.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1528 Merging Gateway API Admins and Maintainers, Moving Harry to Emeritus
  OWNERS
  OWNERS_ALIASES
  README.md
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1529 chore: cleanup litespeed section on implementations page
  site-src/implementations.md
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1499 Add "Programmed" Gateway condition, move "Ready" to extended conformance
  apis/v1alpha2/gateway_types.go
  apis/v1beta1/gateway_types.go
  conformance/tests/gateway-secret-missing-reference-grant.go
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
  conformance/tests/gateway-secret-reference-grant-specific.go
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-disallowed-kind.go
  conformance/tests/httproute-exact-path-matching.go
  conformance/tests/httproute-header-matching.go
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-invalid-backendref-nonexistent.go
  conformance/tests/httproute-invalid-backendref-unknown-kind.go
  conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
  conformance/tests/httproute-invalid-reference-grant.go
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching.go
  conformance/tests/httproute-method-matching.go
  conformance/tests/httproute-query-param-matching.go
  conformance/tests/httproute-reference-grant.go
  conformance/tests/httproute-request-header-modifier.go
  conformance/tests/httproute-response-header-modifier.go
  conformance/tests/httproute-simple-same-namespace.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/suite/suite.go
Labels: kind/feature, ok-to-test, kind/api-change, approved, cncf-cla: yes, lgtm, size/L

#1530 Minor GRPCRoute implementation fixes
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
Labels: kind/bug, ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1535 fix: cherry pick to re-apply google implementations page
  site-src/implementations.md
Labels: documentation, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1516 feat: add `RouteReasonNoMatchingParent`
  apis/v1beta1/shared_types.go
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.yaml
  conformance/utils/suite/suite.go
Labels: kind/feature, ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1522 Fix job problem of build docker image
  hack/build-and-push.sh
Labels: kind/bug, approved, size/S, needs-ok-to-test, cncf-cla: yes, lgtm

#1544 Rename httproute-invalid-reference-grant to reflect partial validity
  conformance/tests/httproute-partially-invalid-via-reference-grant.go
  conformance/tests/httproute-partially-invalid-via-reference-grant.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm, area/conformance

#1546 conformance/tests: fix manifest file name
  conformance/tests/httproute-partially-invalid-via-reference-grant.go
Labels: size/XS, approved, cncf-cla: yes, lgtm, area/conformance

#1542 Remove -f to use default value for docker build job fix
  hack/build-and-push.sh
Labels: kind/bug, size/XS, approved, needs-ok-to-test, cncf-cla: yes, lgtm

#1550 fix: overview meetings links
  site-src/geps/overview.md
Labels: size/XS, approved, cncf-cla: yes, lgtm

#1549 chore: add docker buildx verify
  Makefile
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#1551 chore: clean buildx verify and run go mod tidy
  Makefile
  go.mod
  go.sum
Labels: kind/bug, approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1552 fix: multi-push ci failed
  cloudbuild.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1557 Typo in ReferenceGrant documentation.
  site-src/api-types/referencegrant.md
Labels: size/XS, approved, needs-ok-to-test, kind/documentation, cncf-cla: yes, lgtm

#1558 Correct util/translator function documentation
  apis/v1alpha2/util/translator/shared_types.go
  apis/v1beta1/util/translator/shared_types.go
Labels: approved, needs-ok-to-test, size/M, cncf-cla: yes, lgtm

#1566 fix: typo: indent
  site-src/geps/gep-1323.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm
