Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-07, with the labels that each got.

#1163 conformance: add request header modifier test
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-exact-path-matching.go
  conformance/tests/httproute-header-matching.go
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-invalid-reference-grant.go
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching.go
  conformance/tests/httproute-reference-grant.go
  conformance/tests/httproute-request-header-modifier.go
  conformance/tests/httproute-request-header-modifier.yaml
  conformance/tests/httproute-simple-same-namespace.go
  conformance/utils/http/http.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L, area/conformance

#1251 Fix typos and remove obsolete Service APIs reference
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/shared_types.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  conformance/utils/suite/suite.go
  site-src/geps/gep-1016.md
  site-src/guides/getting-started.md
  site-src/implementations.md
  site-src/index.md
Labels: approved, size/S, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1255 Updating release documentation to include release notes generator
  RELEASE.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1249 conformance: wait for all conditions, not just status code
  conformance/utils/http/http.go
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm, kind/flake

#1253 add HTTP query param matching conformance test
  conformance/tests/httproute-query-param-matching.go
  conformance/tests/httproute-query-param-matching.yaml
  conformance/utils/http/http.go
  conformance/utils/suite/suite.go
Labels: approved, cncf-cla: yes, lgtm, size/L, area/conformance

#1252 Returning NamedAddress type and marking it deprecated
  apis/v1alpha2/shared_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Labels: kind/bug, approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1258 Enum details update
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/shared_types.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm, size/L

#1254 Adding changelog for v0.5.0-rc2
  CHANGELOG.md
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  pkg/generator/main.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, lgtm

#1260 conformance: fix copy-paste errors in unknown backend kind test
  conformance/tests/httproute-invalid-backendref-unknown-kind.go
  conformance/tests/httproute-invalid-backendref-unknown-kind.yaml
Labels: approved, size/S, cncf-cla: yes, lgtm, area/conformance

#1262 Adding GAMMA leads to OWNERS
  OWNERS
  OWNERS_ALIASES
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1264 Adding changelog for v0.5.0, bumping versions to v0.5.0
  CHANGELOG.md
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/webhook/admission_webhook.yaml
  hack/verify-examples-kind.sh
  pkg/generator/main.go
Labels: kind/api-change, approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1245 Update examples to v1beta1
  examples/experimental/v1alpha2/http-redirect-rewrite/httproute-redirect-full.yaml
  examples/experimental/v1alpha2/http-redirect-rewrite/httproute-redirect-https.yaml
  examples/experimental/v1alpha2/http-redirect-rewrite/httproute-redirect-prefix.yaml
  examples/experimental/v1alpha2/http-redirect-rewrite/httproute-rewrite-path.yaml
  examples/experimental/v1alpha2/http-redirect-rewrite/httproute-rewrite.yaml
  examples/experimental/v1beta1/http-redirect-rewrite/httproute-redirect-full.yaml
  examples/experimental/v1beta1/http-redirect-rewrite/httproute-redirect-https.yaml
  examples/experimental/v1beta1/http-redirect-rewrite/httproute-redirect-prefix.yaml
  examples/experimental/v1beta1/http-redirect-rewrite/httproute-rewrite-path.yaml
  examples/experimental/v1beta1/http-redirect-rewrite/httproute-rewrite.yaml
  examples/v1alpha2/basic-http.yaml
  examples/v1alpha2/cross-namespace-routing/0-namespaces.yaml
  examples/v1alpha2/cross-namespace-routing/gateway.yaml
  examples/v1alpha2/cross-namespace-routing/site-route.yaml
  examples/v1alpha2/cross-namespace-routing/store-route.yaml
  examples/v1alpha2/http-filter.yaml
  examples/v1alpha2/http-route-attachment/gateway-namespaces.yaml
  examples/v1alpha2/http-route-attachment/gateway-strict.yaml
  examples/v1alpha2/http-route-attachment/httproute.yaml
  examples/v1alpha2/http-routing/bar-httproute.yaml
  examples/v1alpha2/http-routing/foo-httproute.yaml
  examples/v1alpha2/http-routing/gateway.yaml
  examples/v1alpha2/simple-gateway/gateway.yaml
  examples/v1alpha2/simple-gateway/httproute.yaml
  examples/v1alpha2/tls-basic.yaml
  examples/v1alpha2/traffic-splitting/simple-split.yaml
  examples/v1alpha2/traffic-splitting/traffic-split-1.yaml
  examples/v1alpha2/traffic-splitting/traffic-split-2.yaml
  examples/v1alpha2/traffic-splitting/traffic-split-3.yaml
  examples/v1alpha2/wildcard-tls-gateway.yaml
  examples/v1beta1/basic-http.yaml
  examples/v1beta1/cross-namespace-routing/0-namespaces.yaml
  examples/v1beta1/cross-namespace-routing/gateway.yaml
  examples/v1beta1/cross-namespace-routing/site-route.yaml
  examples/v1beta1/cross-namespace-routing/store-route.yaml
  examples/v1beta1/http-filter.yaml
  examples/v1beta1/http-routing/bar-httproute.yaml
  examples/v1beta1/http-routing/foo-httproute.yaml
  examples/v1beta1/http-routing/gateway.yaml
  examples/v1beta1/simple-gateway/gateway.yaml
  examples/v1beta1/simple-gateway/httproute.yaml
  examples/v1beta1/tls-basic.yaml
  examples/v1beta1/traffic-splitting/simple-split.yaml
  examples/v1beta1/traffic-splitting/traffic-split-1.yaml
  examples/v1beta1/traffic-splitting/traffic-split-2.yaml
  examples/v1beta1/traffic-splitting/traffic-split-3.yaml
  examples/v1beta1/wildcard-tls-gateway.yaml
  site-src/api-types/gatewayclass.md
  site-src/api-types/httproute.md
  site-src/concepts/api-overview.md
  site-src/faq.md
  site-src/guides/http-redirect-rewrite.md
  site-src/guides/http-routing.md
  site-src/guides/multiple-ns.md
  site-src/guides/simple-gateway.md
  site-src/guides/tcp.md
  site-src/guides/tls.md
  site-src/guides/traffic-splitting.md
Labels: ok-to-test, approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1263 Adding v0.5.0 blog post
  mkdocs.yml
  site-src/blog/2022/graduating-to-beta.md
  site-src/blog/index.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1268 Updating Getting Started Guide for v0.5.0
  site-src/guides/getting-started.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1270 docs: Update the status of the Apache APISIX Ingress implementation
  site-src/implementations.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1277 Adding GKE contact information to implementations page
  site-src/implementations.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1278 Clarifying which kinds of bugs should be filed in this repo
  .github/ISSUE_TEMPLATE/bug.md
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1276 Bumping versions to v0.6.0-dev
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  pkg/generator/main.go
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1281 Add GAMMA meetings
  site-src/contributing/community.md
  site-src/contributing/gamma.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1280 [docs] Cilium Gateway API implementation
  site-src/implementations.md
Labels: approved, size/S, needs-ok-to-test, kind/documentation, cncf-cla: yes, lgtm

#1288 Update to go 1.19rc2 to match upstream (and fix codegen)
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: size/XS, approved, kind/failing-test, kind/cleanup, cncf-cla: yes, lgtm

#1286 update Contour's implementation entry
  site-src/implementations.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm
