Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-08, with the labels that each got.

#1115 Implement GRPCRoute (GEP 1016)
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  apis/v1alpha2/zz_generated.register.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/kustomization.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  pkg/client/clientset/versioned/typed/apis/v1alpha2/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_grpcroute.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/grpcroute.go
  pkg/client/informers/externalversions/apis/v1alpha2/grpcroute.go
  pkg/client/informers/externalversions/apis/v1alpha2/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apis/v1alpha2/expansion_generated.go
  pkg/client/listers/apis/v1alpha2/grpcroute.go
Labels: kind/feature, ok-to-test, kind/api-change, approved, cncf-cla: yes, lgtm, size/XL

#1293 Fixes broken link on Security Model docs
  site-src/concepts/security-model.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1290 Rectified Conformance Test Name Generation
  conformance/tests/httproute-exact-path-matching.go
  conformance/tests/httproute-header-matching.go
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching.go
  conformance/tests/httproute-query-param-matching.go
  conformance/tests/httproute-request-header-modifier.go
  conformance/utils/http/http.go
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1292 make timeout configurable
  conformance/tests/gateway-secret-invalid-reference-grant.go
  conformance/tests/gateway-secret-missing-reference-grant.go
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
  conformance/tests/gateway-secret-reference-grant-specific.go
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-disallowed-kind.go
  conformance/tests/httproute-exact-path-matching.go
  conformance/tests/httproute-header-matching.go
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-invalid-backendref-nonexistent.go
  conformance/tests/httproute-invalid-backendref-unknown-kind.go
  conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
  conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
  conformance/tests/httproute-invalid-reference-grant.go
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching.go
  conformance/tests/httproute-query-param-matching.go
  conformance/tests/httproute-reference-grant.go
  conformance/tests/httproute-request-header-modifier.go
  conformance/tests/httproute-simple-same-namespace.go
  conformance/utils/config/timeout.go
  conformance/utils/http/http.go
  conformance/utils/kubernetes/apply.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/roundtripper/roundtripper.go
  conformance/utils/suite/suite.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#1298 conformance/utils/suite: Move timeout setup before building roundtripper
  conformance/utils/suite/suite.go
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1302 Fix import naming.
  apis/v1beta1/validation/gateway.go
  apis/v1beta1/validation/gateway_test.go
  apis/v1beta1/validation/gatewayclass.go
  apis/v1beta1/validation/gatewayclass_test.go
  apis/v1beta1/validation/httproute.go
  apis/v1beta1/validation/httproute_test.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/XL

#1301 Remove duplicate import and fix package references.
  apis/v1alpha2/validation/httproute_test.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1304 Remove duplicate import.
  apis/v1beta1/validation/httproute_test.go
Labels: size/XS, approved, needs-ok-to-test, kind/cleanup, cncf-cla: yes, lgtm

#1305 Conformance: fix Listener ConditionReason
  conformance/tests/gateway-secret-invalid-reference-grant.go
  conformance/tests/gateway-secret-missing-reference-grant.go
Labels: kind/bug, size/XS, approved, needs-ok-to-test, cncf-cla: yes, lgtm

#1303 Remove extra leading slashes from comment.
  apis/v1alpha2/validation/httproute.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1309 Link to cilium updated
  site-src/implementations.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1306 Export DefaultTimeoutConfig.
  conformance/utils/config/timeout.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1307 Remove extra comment slashes.
  apis/v1beta1/validation/httproute.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1316 All route ResolvedRefs reasons added to docs
  apis/v1alpha2/shared_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1321 Route ResolvedRefs reason godoc updated
  apis/v1alpha2/shared_types.go
  apis/v1beta1/shared_types.go
Labels: size/XS, approved, needs-ok-to-test, kind/documentation, cncf-cla: yes, lgtm

#1319 broken link under site_src
  site-src/api-types/gatewayclass.md
  site-src/api-types/httproute.md
  site-src/api-types/referencegrant.md
  site-src/blog/2021/introducing-v1alpha2.md
  site-src/blog/index.md
  site-src/contributing/enhancement-requests.md
  site-src/contributing/gamma.md
  site-src/contributing/gep.md
Labels: kind/bug, approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1322 docs: update README.md about v0.5.0 release
  README.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1327 Replace echoserver with arm64 compatible version
  conformance/base/manifests.yaml
Labels: kind/feature, approved, size/S, kind/failing-test, cncf-cla: yes, lgtm

#1332 Clarify BackendObjectReference Port field godoc
  apis/v1alpha2/object_reference_types.go
  apis/v1beta1/object_reference_types.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1299 Adding docs covering conformance
  README.md
  mkdocs.yml
  site-src/concepts/conformance.md
  site-src/concepts/guidelines.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1325 Add GEP describing goals for service mesh in Gateway API
  site-src/geps/gep-1324.md
  site-src/geps/images/1324-backend-ref.png
  site-src/geps/images/1324-decomposed-view-of-service.png
  site-src/geps/images/1324-resource-view-of-service.png
  site-src/geps/images/1324-service-frontend.png
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/gep, area/mesh

#1337 Add converter pkg to house type conversion helpers
  apis/v1alpha2/util/translator/httproute.go
  apis/v1alpha2/util/translator/httproute_test.go
  apis/v1alpha2/util/translator/shared_types.go
  apis/v1alpha2/util/translator/shared_types_test.go
  apis/v1alpha2/validation/httproute_test.go
  apis/v1beta1/util/translator/httproute.go
  apis/v1beta1/util/translator/httproute_test.go
  apis/v1beta1/util/translator/shared_types.go
  apis/v1beta1/util/translator/shared_types_test.go
  apis/v1beta1/validation/httproute_test.go
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1342 gep-1234: Formatting fixes around use cases for GAMMA initiative
  site-src/geps/gep-1324.md
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#1334 conformance: listener references invalid secret
  conformance/tests/gateway-secret-missing-referenced-secret.go
  conformance/tests/gateway-secret-missing-referenced-secret.yaml
Labels: kind/feature, ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1345 docs: display beta before alpha in API spec
  hack/api-docs/pkg.tpl
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1339 feat: validate port in backendRef for TCPRoute, UDPRoute, and TLSRoute (v1alpha2)
  apis/v1alpha2/validation/common.go
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/tcproute.go
  apis/v1alpha2/validation/tcproute_test.go
  apis/v1alpha2/validation/tlsroute.go
  apis/v1alpha2/validation/tlsroute_test.go
  apis/v1alpha2/validation/udproute.go
  apis/v1alpha2/validation/udproute_test.go
  pkg/admission/server.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/XL

#1354 conformance: fix GatewaySecretReferenceGrantAllInNamespace resources
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
Labels: kind/bug, size/XS, approved, kind/failing-test, cncf-cla: yes, lgtm

#1351 Release 0.5.x: Cherry-pick #1305
  conformance/tests/gateway-secret-invalid-reference-grant.go
  conformance/tests/gateway-secret-missing-reference-grant.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1352 Add utils to translate custom types
  apis/v1alpha2/util/translator/shared_types.go
  apis/v1beta1/util/translator/shared_types.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1353 Docs updates around release process
  RELEASE.md
  site-src/concepts/versioning.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1343 Address comments made after PR was closed
  site-src/geps/gep-1324.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1344 docs: couple of ReferenceGrant cleanups
  hack/api-docs/config.json
  site-src/api-types/referencegrant.md
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1356 conformance: listener `invalidRouteKind`
  conformance/tests/gateway-unsupported-route-kind.go
  conformance/tests/gateway-unsupported-route-kind.yaml
Labels: kind/feature, approved, needs-ok-to-test, cncf-cla: yes, lgtm, size/L

#1357 Fixing docs links that incorrectly had site-src/ prefix
  site-src/api-types/httproute.md
  site-src/api-types/referencegrant.md
  site-src/contributing/enhancement-requests.md
  site-src/contributing/gamma.md
  site-src/contributing/gep.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1358 Revert "broken_site_src"
  site-src/api-types/gatewayclass.md
  site-src/api-types/httproute.md
  site-src/api-types/referencegrant.md
  site-src/blog/2021/introducing-v1alpha2.md
  site-src/blog/index.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1359 Add help info to NGINX Kubernetes Gateway implementation section
  site-src/implementations.md
Labels: size/XS, approved, needs-ok-to-test, kind/documentation, cncf-cla: yes, lgtm

#1335 Add time elapsed message to awaitConvergence
  conformance/utils/http/http.go
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1350 gep-1324: add a definition of "gateway" to glossary
  site-src/geps/gep-1324.md
Labels: kind/design, approved, size/S, cncf-cla: yes, lgtm

#1349 Documenting supported versions
  site-src/concepts/versioning.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1363 Print conditions for failed conformance tests
  conformance/utils/kubernetes/helpers.go
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1333 Add Provisional GEP-1282 document
  site-src/geps/gep-1282.md
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/gep

#1365 Fixing webhook config to watch v1beta1
  config/webhook/admission_webhook.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1367 Print conditions for failed conformance tests
  conformance/utils/http/http.go
Labels: kind/bug, size/XS, approved, needs-ok-to-test, cncf-cla: yes, lgtm

#1368 release-0.5: Cherry pick #1365 - Fixing webhook config to watch v1beta1
  config/webhook/admission_webhook.yaml
Labels: kind/bug, size/XS, approved, needs-ok-to-test, cncf-cla: yes, lgtm

#1369 conformance: print Reason if Status doesn't match
  conformance/utils/kubernetes/helpers.go
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm
