Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-01, with the labels that each got.

#980 Fixing accidental escaping of namespace/name in docs
  apis/v1alpha1/httproute_types.go
  apis/v1alpha1/tcproute_types.go
  apis/v1alpha1/tlsroute_types.go
  apis/v1alpha1/udproute_types.go
  apis/v1alpha2/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  site-src/geps/gep-713.md
  site-src/v1alpha2/references/policy-attachment.md
Labels: kind/bug, approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#956 Introduce wildcardhostname field
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/validation/httproute_test.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  hack/invalid-examples/v1alpha2/httproute/invalid-httredirect-hostname.yaml
Labels: kind/bug, ok-to-test, kind/api-change, approved, size/M, cncf-cla: yes, lgtm

#981 Cherry Pick #956 into release-0.4
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
  hack/invalid-examples/v1alpha2/httproute/invalid-httredirect-hostname.yaml
Labels: kind/bug, approved, size/M, cncf-cla: yes, lgtm

#983 Fix formatting for cross namespaces references.
  site-src/v1alpha2/references/cross-namespace-references.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#965 Updating changelog for v0.4.1
  CHANGELOG.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#982 Rename ParentRef to be consistent with other reference types.
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#989 Fix listener allowed kinds documentation.
  apis/v1alpha2/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/stable/gateway.networking.k8s.io_gateways.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#991 Migrate kube-webhook-certgen to k8s.gcr.io/ingress-nginx:v1.1.1
  deploy/certificate_config.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#976 feat: implement L4 traffic matching
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/tcproute_types.go
  apis/v1alpha2/udproute_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  examples/experimental/v1alpha2/traffic-matching-tcp.yaml
  hack/verify-examples-kind.sh
  site-src/geps/gep-735.md
  site-src/v1alpha2/guides/tcp.md
Labels: kind/feature, kind/api-change, approved, cncf-cla: yes, lgtm, size/L

#1001 Fix v1alpha2 "HTTP routing" example
  examples/v1alpha2/http-routing/bar-httproute.yaml
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#987 Clarify that listener names are unique.
  apis/v1alpha2/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/stable/gateway.networking.k8s.io_gateways.yaml
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#966 Adding GEP 957 for port matching support.
  site-src/geps/gep-957.md
Labels: ok-to-test, kind/api-change, approved, cncf-cla: yes, lgtm, size/L, kind/gep

#969 Initial Conformance Tests for Gateway API
  Makefile
  conformance/base/manifests.yaml
  conformance/conformance_test.go
  conformance/tests/httproute-simple-same-namespace.go
  conformance/tests/httproute-simple-same-namespace.yaml
  conformance/tests/main.go
  conformance/utils/http/http.go
  conformance/utils/kubernetes/apply.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/roundtripper/roundtripper.go
  conformance/utils/suite/suite.go
  go.mod
  go.sum
  site-src/concepts/guidelines.md
Labels: kind/feature, approved, size/XXL, cncf-cla: yes, lgtm
