Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-06, with the labels that each got.

#1173 Clarifying that wildcard hostname matching is suffix matching
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_gateways.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-listener-hostname-matching.yaml
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm, area/conformance

#1171 Adding validation to ensure prefix path match exists for path modifier
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/httproute_test.go
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1188 Rename files to reflect ReferencePolicy -> ReferenceGrant
  apis/v1alpha2/referencegrant_types.go
  conformance/tests/httproute-invalid-reference-grant.go
  conformance/tests/httproute-invalid-reference-grant.yaml
  conformance/tests/httproute-reference-grant.go
  conformance/tests/httproute-reference-grant.yaml
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1178 Update AddressType definition to add domain-prefixed strings as an option
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/gateway_test.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/stable/gateway.networking.k8s.io_gateways.yaml
Labels: kind/api-change, approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1186 Fixing docs to have subheaders again, removing custom alignment
  examples/v1alpha1/basic-http.yaml
  examples/v1alpha1/basic-tcp.yaml
  examples/v1alpha1/cross-namespace-routing/gateway.yaml
  examples/v1alpha1/cross-namespace-routing/site-route.yaml
  examples/v1alpha1/cross-namespace-routing/store-route.yaml
  examples/v1alpha1/http-filter.yaml
  examples/v1alpha1/http-routing/bar-httproute.yaml
  examples/v1alpha1/http-routing/foo-httproute.yaml
  examples/v1alpha1/http-routing/gateway.yaml
  examples/v1alpha1/http-trafficsplit.yaml
  examples/v1alpha1/simple-gateway/gateway.yaml
  examples/v1alpha1/simple-gateway/httproute.yaml
  examples/v1alpha1/tls-basic.yaml
  examples/v1alpha1/tls-cert-in-route.yaml
  examples/v1alpha1/traffic-splitting/simple-split.yaml
  examples/v1alpha1/traffic-splitting/traffic-split-1.yaml
  examples/v1alpha1/traffic-splitting/traffic-split-2.yaml
  examples/v1alpha1/traffic-splitting/traffic-split-3.yaml
  examples/v1alpha1/upstream-tls.yaml
  examples/v1alpha1/wildcard-tls-gateway.yaml
  examples/v1alpha2/basic-http.yaml
  examples/v1alpha2/basic-tcp.yaml
  examples/v1alpha2/cross-namespace-routing/0-namespaces.yaml
  examples/v1alpha2/cross-namespace-routing/gateway.yaml
  examples/v1alpha2/cross-namespace-routing/site-route.yaml
  examples/v1alpha2/cross-namespace-routing/store-route.yaml
  examples/v1alpha2/http-filter.yaml
  examples/v1alpha2/http-route-attachment/gateway-namespaces.yaml
  examples/v1alpha2/http-route-attachment/gateway-strict.yaml
  examples/v1alpha2/http-route-attachment/httproute.yaml
  examples/v1alpha2/http-routing/bar-httproute.yaml
  examples/v1alpha2/http-routing/foo-httproute.yaml
  examples/v1alpha2/http-routing/gateway.yaml
  examples/v1alpha2/reference-grant.yaml
  examples/v1alpha2/simple-gateway/gateway.yaml
  examples/v1alpha2/simple-gateway/httproute.yaml
  examples/v1alpha2/tls-basic.yaml
  examples/v1alpha2/tls-cert-cross-namespace.yaml
  examples/v1alpha2/traffic-splitting/simple-split.yaml
  examples/v1alpha2/traffic-splitting/traffic-split-1.yaml
  examples/v1alpha2/traffic-splitting/traffic-split-2.yaml
  examples/v1alpha2/traffic-splitting/traffic-split-3.yaml
  examples/v1alpha2/wildcard-tls-gateway.yaml
  mkdocs.yml
  requirements.txt
  site-src/css/extra.css
Labels: approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm, size/L

#1182 Renaming stable channel to standard channel
  .gitattributes
  config/crd/kustomization.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/standard/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/standard/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/standard/gateway.networking.k8s.io_udproutes.yaml
  hack/build-install-yaml.sh
  hack/verify-examples-kind.sh
  pkg/generator/main.go
  site-src/concepts/versioning.md
  site-src/geps/gep-820.md
  site-src/geps/gep-922.md
  site-src/v1alpha2/contributing/devguide.md
Labels: kind/api-change, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm, size/L

#1191 docs: refresh kong in implementations.md
  site-src/implementations.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1162 Add HTTP Rewrite and Redirect Filter guide
  apis/v1alpha2/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  examples/experimental/http-redirect-rewrite/httproute-redirect-full.yaml
  examples/experimental/http-redirect-rewrite/httproute-redirect-https.yaml
  examples/experimental/http-redirect-rewrite/httproute-redirect-prefix.yaml
  examples/experimental/http-redirect-rewrite/httproute-rewrite-path.yaml
  examples/experimental/http-redirect-rewrite/httproute-rewrite.yaml
  mkdocs.yml
  site-src/v1alpha2/api-types/httproute.md
  site-src/v1alpha2/guides/getting-started.md
  site-src/v1alpha2/guides/http-redirect-rewrite.md
Labels: ok-to-test, approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1189 Clarifying how ReplacePrefixMatch works
  apis/v1alpha2/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, size/S, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1192 recopy the v1beta1 types
  apis/v1beta1/doc.go
  apis/v1beta1/gateway_types.go
  apis/v1beta1/gatewayclass_types.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/object_reference_types.go
  apis/v1beta1/shared_types.go
Labels: kind/feature, approved, size/XXL, tide/merge-method-squash, cncf-cla: yes, lgtm

#1199 deps: update k8s.io modules to v0.24
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_gateway.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_gatewayclass.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_httproute.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_referencegrant.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_tcproute.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_tlsroute.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_udproute.go
  pkg/client/clientset/versioned/typed/apis/v1beta1/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1beta1/fake/fake_gateway.go
  pkg/client/clientset/versioned/typed/apis/v1beta1/fake/fake_gatewayclass.go
  pkg/client/clientset/versioned/typed/apis/v1beta1/fake/fake_httproute.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1203 fix: broken kustomize for crd deployment
  config/crd/experimental/kustomization.yaml
  config/crd/kustomization.yaml
  hack/verify-examples-kind.sh
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1204 Replacing webhook validation with CRD validation for AddressType
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/gateway_test.go
  apis/v1beta1/shared_types.go
  apis/v1beta1/validation/gateway.go
  apis/v1beta1/validation/gateway_test.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1144 conformance: add hostname intersection test
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-hostname-intersection.yaml
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L, area/conformance

#1158 conformance: add test cases for Gateway->Secret ReferenceGrant
  conformance/base/manifests.yaml
  conformance/tests/gateway-secret-invalid-reference-grant.go
  conformance/tests/gateway-secret-invalid-reference-grant.yaml
  conformance/tests/gateway-secret-missing-reference-grant.go
  conformance/tests/gateway-secret-missing-reference-grant.yaml
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.yaml
  conformance/tests/gateway-secret-reference-grant-specific.go
  conformance/tests/gateway-secret-reference-grant-specific.yaml
  conformance/tests/httproute-disallowed-kind.yaml
  conformance/tests/httproute-listener-hostname-matching.yaml
  conformance/utils/kubernetes/apply.go
  conformance/utils/kubernetes/certificate.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/suite/suite.go
Labels: kind/feature, ok-to-test, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/XL

#1208 Move error status code from 404 to 500
  apis/v1alpha2/httproute_types.go
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: ok-to-test, kind/api-change, approved, size/S, cncf-cla: yes, lgtm

#1190 docs: add v0.5.0 release CHANGELOG entry
  CHANGELOG.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1212 Preparing v0.5.0-rc1 for release
  CHANGELOG.md
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  pkg/generator/main.go
Labels: kind/feature, kind/api-change, approved, size/S, cncf-cla: yes, lgtm

#1213 Fixing changelog title for v0.5.0-rc1
  CHANGELOG.md
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1216 add back ReferencePolicies YAML to experimental kustomization.yaml
  config/crd/experimental/kustomization.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1221 conformance: Use valid YAML string for gatewayClassName placeholder
  conformance/tests/httproute-hostname-intersection.yaml
Labels: size/XS, approved, needs-ok-to-test, kind/cleanup, cncf-cla: yes, lgtm

#1226 docs: minor update to community bugs and feedback
  site-src/v1alpha2/contributing/community.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1233 Fill in missing policy attachment example
  site-src/v1alpha2/references/policy-attachment.md
Labels: kind/bug, ok-to-test, approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1232 Generate working release/experimental-install.yaml
  hack/build-install-yaml.sh
Labels: ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1234 Add experimental warning for resources that are experimental
  site-src/blog/2021/introducing-v1alpha2.md
  site-src/concepts/api-overview.md
  site-src/v1alpha2/api-types/referencegrant.md
  site-src/v1alpha2/guides/tcp.md
  site-src/v1alpha2/guides/tls.md
Labels: approved, needs-ok-to-test, size/M, kind/documentation, cncf-cla: yes, lgtm

#1228 Adds new tiny type for HTTPRoute Listeners in conformance tests
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-exact-path-matching.go
  conformance/tests/httproute-header-matching.go
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-invalid-reference-grant.go
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching.go
  conformance/tests/httproute-reference-grant.go
  conformance/tests/httproute-simple-same-namespace.go
  conformance/utils/kubernetes/helpers.go
Labels: kind/bug, ok-to-test, approved, kind/failing-test, size/M, cncf-cla: yes, lgtm

#1236 Replace PolicyAttachment hierarchy example with correct diagram
  site-src/v1alpha2/references/images/policy-hierarchy.png
  site-src/v1alpha2/references/policy-attachment.md
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#1196 chore: updates for default branch rename
  CHANGELOG.md
  Makefile
  OWNERS
  OWNERS_ALIASES
  RELEASE.md
  cloudbuild.yaml
  hack/build-and-push.sh
  mkdocs.yml
  netlify.toml
  site-src/concepts/versioning.md
Labels: approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1237 conformance: fix HTTPRouteListenerHostnameMatching
  conformance/tests/httproute-listener-hostname-matching.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#1239 fix ReferencePolicyList.Items type
  apis/v1alpha2/referencepolicy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
Labels: ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1231 Adding Shane Utt as Gateway API Maintainer
  OWNERS_ALIASES
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1230 apis: validate header and query param matches
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/httproute_test.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/validation/httproute.go
  apis/v1beta1/validation/httproute_test.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1241 Ensure that "Supports:" statements stand alone in the docs
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/tcproute_types.go
  apis/v1alpha2/tlsroute_types.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, size/S, needs-ok-to-test, kind/documentation, cncf-cla: yes, lgtm

#1181 Update ReferenceGrant docs to include Gateway -> Secret use case
  apis/v1alpha2/object_reference_types.go
  apis/v1alpha2/referencegrant_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  site-src/api-types/referencegrant.md
Labels: approved, needs-ok-to-test, size/M, kind/documentation, cncf-cla: yes, lgtm
