Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-12, with the labels that each got.

#1559 Update changelog to add v0.6.0-rc1
  CHANGELOG.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1570 Finish preparing for v0.6.0-rc1 release
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  pkg/generator/main.go
Labels: size/XS, approved, cncf-cla: yes, lgtm

#1571 Update release docs
  RELEASE.md
Labels: approved, size/S, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1572 Fix webhook update script for semver
  config/webhook/admission_webhook.yaml
  hack/update-webhook-yaml.sh
Labels: kind/bug, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1569 chore: cleanup for #1538
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/referencegrant_types.go
  apis/v1alpha2/util/translate/httproute.go
  apis/v1alpha2/util/translate/httproute_test.go
  apis/v1alpha2/util/translate/shared_types.go
  apis/v1alpha2/util/translate/shared_types_test.go
  apis/v1alpha2/validation/common.go
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/grpcroute.go
  apis/v1alpha2/validation/httproute_test.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/referencegrant_types.go
  apis/v1beta1/shared_types.go
  apis/v1beta1/util/translate/httproute.go
  apis/v1beta1/util/translate/httproute_test.go
  apis/v1beta1/util/translate/shared_types.go
  apis/v1beta1/util/translate/shared_types_test.go
  apis/v1beta1/validation/gateway.go
  apis/v1beta1/validation/httproute_test.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1575 Updating Terminology in ReferenceGrant and Release Channel Diagrams
  site-src/api-types/referencegrant.md
  site-src/concepts/versioning.md
  site-src/images/lifecycle-new-fields.png
  site-src/images/lifecycle-new-fields.svg
  site-src/images/referencegrant-simple.png
  site-src/images/referencegrant-simple.svg
  site-src/images/release-channel-overlap.png
  site-src/images/release-channel-overlap.svg
Labels: approved, size/S, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1577 Update typo in security-model.md
  site-src/concepts/security-model.md
Labels: size/XS, approved, needs-ok-to-test, kind/documentation, cncf-cla: yes, lgtm

#1576 v0.6.0 review cleanup
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/util/translate/httproute_test.go
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/gateway_test.go
  apis/v1alpha2/validation/grpcroute_test.go
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/httproute_test.go
  apis/v1beta1/gateway_types.go
  apis/v1beta1/validation/httproute.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/XL

#1580 Rework GRPCRoute API docs.
  apis/v1alpha2/grpcroute_types.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
Labels: ok-to-test, approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1560 Update GEP-1364 to Standard implementation
  mkdocs.yml
  site-src/geps/gep-1364.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm, kind/gep

#1585 Replacing util/translate with generic func, misc cleanup from API review
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/util/translate/httproute.go
  apis/v1alpha2/util/translate/httproute_test.go
  apis/v1alpha2/util/translate/shared_types.go
  apis/v1alpha2/util/translate/shared_types_test.go
  apis/v1alpha2/validation/common.go
  apis/v1alpha2/validation/httproute_test.go
  apis/v1beta1/util/translate/httproute.go
  apis/v1beta1/util/translate/httproute_test.go
  apis/v1beta1/util/translate/shared_types.go
  apis/v1beta1/util/translate/shared_types_test.go
  apis/v1beta1/validation/common.go
  apis/v1beta1/validation/httproute_test.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/XL

#1589 Fix filename in HTTPRouteInvalidParentRefNotMatchingListenerPort test
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
Labels: kind/bug, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1591 conformance: Update HTTPRouteInvalidParentRefNotMatchingListenerPort
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.yaml
Labels: ok-to-test, size/XS, approved, kind/failing-test, cncf-cla: yes, lgtm

#1556 added redirect tests for core redirect features
  conformance/tests/httproute-request-redirect.go
  conformance/tests/httproute-request-redirect.yaml
  conformance/utils/http/http.go
  conformance/utils/roundtripper/roundtripper.go
Labels: kind/feature, ok-to-test, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, area/conformance

#1597 Bump kind to v0.17.0
  hack/verify-examples-kind.sh
Labels: ok-to-test, approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1601 v0.6.0 review updates
  apis/v1alpha2/validation/tlsroute_test.go
  apis/v1alpha2/validation/udproute_test.go
  apis/v1alpha2/validation/utils_test.go
  apis/v1beta1/util/validation/common_test.go
  apis/v1beta1/validation/common.go
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  go.mod
  go.sum
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1602 use Programmed instead of Ready for Gateway print column
  apis/v1alpha2/gateway_types.go
  apis/v1beta1/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1603 docs: dev notes about prio labels
  site-src/contributing/devguide.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1604 Update types to fix API review feedback
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1beta1/gateway_types.go
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1599 Tightening GRPCRoute validation, fixing gaps in HTTPRoute and Gateway webhook validation
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/grpcroute.go
  apis/v1alpha2/validation/grpcroute_test.go
  apis/v1alpha2/validation/httproute.go
  apis/v1beta1/validation/gateway.go
  apis/v1beta1/validation/httproute.go
  apis/v1beta1/validation/httproute_test.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  hack/invalid-examples/v1alpha2/grpcroute/invalid-method.yaml
  hack/invalid-examples/v1alpha2/grpcroute/invalid-service.yaml
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/XL

#1606 Adding Changelog for v0.6.0-rc2, updating CRD approval annotations
  CHANGELOG.md
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  pkg/generator/main.go
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1595 Bump k8s.io deps to v0.26.0
  go.mod
  go.sum
  pkg/client/clientset/versioned/clientset.go
  pkg/client/informers/externalversions/factory.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1608 Finish preparing for v0.6.0-rc2 release
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  config/webhook/admission_webhook.yaml
  hack/verify-examples-kind.sh
  pkg/generator/main.go
Labels: ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1609 Update istio implementation info
  site-src/implementations.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1586 Assert observedGeneration is incremented in Status.Conditions.
  conformance/tests/gateway-observed-generation-bump.go
  conformance/tests/gateway-observed-generation-bump.yaml
  conformance/tests/gatewayclass-observed-generation-bump.go
  conformance/tests/gatewayclass-observed-generation-bump.yaml
  conformance/tests/httproute-observed-generation-bump.go
  conformance/tests/httproute-observed-generation-bump.yaml
  conformance/utils/kubernetes/apply.go
  conformance/utils/kubernetes/apply_test.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/suite/suite.go
Labels: ok-to-test, kind/api-change, approved, tide/merge-method-squash, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1614 docs: add v0.6.0 changelog entry
  CHANGELOG.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1617 conformance: do not use (and mutate) DefaultClient
  conformance/utils/roundtripper/roundtripper.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1610 Bump controller-runtime to v0.14.1
  go.mod
  go.sum
Labels: ok-to-test, approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1620 Add BIG-IP Kubernetes Gateway to list of implementations
  site-src/implementations.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1621 cleanup: remove ioutil for new goversion
  conformance/utils/roundtripper/roundtripper.go
  pkg/admission/server.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1618 Bump controller-tools to v0.11.1
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  go.mod
  go.sum
  pkg/generator/main.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/XL

#1611 added conformance checks for port, scheme and path (extended + experimental features)
  conformance/tests/httproute-redirect-host-and-status.go
  conformance/tests/httproute-redirect-host-and-status.yaml
  conformance/tests/httproute-redirect-path.go
  conformance/tests/httproute-redirect-path.yaml
  conformance/tests/httproute-redirect-port.go
  conformance/tests/httproute-redirect-port.yaml
  conformance/tests/httproute-redirect-scheme.go
  conformance/tests/httproute-redirect-scheme.yaml
  conformance/utils/http/http.go
  conformance/utils/roundtripper/roundtripper.go
  conformance/utils/suite/suite.go
Labels: ok-to-test, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/XL
