Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-02, with the labels that each got.

#1009 Update Youtube playlist for recorded meetings
  site-src/v1alpha2/contributing/community.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1010 docs: fix references to "Service APIs"
  site-src/faq.md
Labels: ok-to-test, size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1012 Remove redundant word in documentation
  site-src/index.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1013 Change Admitted to Accepted in v1alpha2 docs
  site-src/v1alpha2/api-types/gatewayclass.md
  site-src/v1alpha2/api-types/httproute.md
Labels: ok-to-test, approved, size/S, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1019 API overview fixes
  site-src/concepts/api-overview.md
Labels: ok-to-test, approved, size/S, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1020 docs: fix build with python 3.10
  requirements.txt
Labels: kind/bug, ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1022 docs: update kong in implementations.md
  site-src/implementations.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1002 Implement GEP-957: Destination Port Matching.
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
  examples/experimental/v1alpha2/destination-port-matching-tcp.yaml
  site-src/geps/gep-957.md
Labels: kind/feature, ok-to-test, kind/api-change, approved, size/M, cncf-cla: yes, lgtm

#994 Additional Conformance Tests covering HTTPRoute and Gateway
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-cross-namespace.yaml
  conformance/tests/httproute-invalid-cross-namespace.go
  conformance/tests/httproute-invalid-cross-namespace.yaml
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching-across-routes.yaml
  conformance/tests/httproute-matching.go
  conformance/tests/httproute-matching.yaml
  conformance/utils/http/http.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1024 docs: update kong gateway APIs URL
  site-src/implementations.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1023 feat: allow URL overrides for conformance test manifests
  conformance/tests/httproute-simple-same-namespace.go
  conformance/utils/kubernetes/apply.go
  conformance/utils/suite/suite.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, lgtm

#1025 tcp guide: remove section on metadata based tcp matches
  site-src/v1alpha2/guides/tcp.md
Labels: ok-to-test, size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm
