Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-04, with the labels that each got.

#1071 Cherry pick webhook improvements and bug fixes into release-0.4
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/httproute_test.go
Labels: kind/bug, approved, cncf-cla: yes, lgtm, size/L

#1082 Provide more details on route parentRef in documentation for routes <> Gateways attachment.
  site-src/concepts/api-overview.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1084 clarify core support of secret reference
  apis/v1alpha2/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/stable/gateway.networking.k8s.io_gateways.yaml
Labels: ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1080 Support eventual consistency in conformance tests
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching.go
  conformance/tests/httproute-simple-same-namespace.go
  conformance/utils/http/http.go
Labels: kind/bug, ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#1087 Add NGINX Kubernetes Gateway to list of implementations
  site-src/implementations.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1089 add acnodal epic implementation to docs
  site-src/implementations.md
Labels: ok-to-test, approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1091 verify-examples-kind: reverse path order for kind binary
  hack/verify-examples-kind.sh
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1095 conformance: include Gateway port in WaitForGatewayAddress
  conformance/utils/kubernetes/helpers.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1004 Propose GRPCRoute Resource
  site-src/geps/gep-1016.md
Labels: ok-to-test, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/XL, kind/gep

#1090 Supply single install YAMLs for all required config
  .gitignore
  Makefile
  RELEASE.md
  config/webhook/admission_webhook.yaml
  config/webhook/certificate_config.yaml
  hack/build-install-yaml.sh
  hack/update-webhook-yaml.sh
  hack/verify-examples-kind.sh
Labels: kind/feature, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/L

#1113 Fix markdown rendering for GEP 1016
  site-src/geps/gep-1016.md
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1099 Add integrations sections in docs
  site-src/implementations.md
Labels: ok-to-test, approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1116 Tweaks to HTTPRoute docs (spelling error, heading levels)
  site-src/v1alpha1/api-types/httproute.md
  site-src/v1alpha2/api-types/httproute.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1108 Log when cleaning up test resources
  conformance/utils/kubernetes/apply.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1101 conformance: add option to pass valid ports for listeners and label Namespaces
  conformance/utils/kubernetes/apply.go
  conformance/utils/kubernetes/apply_test.go
  conformance/utils/suite/suite.go
Labels: kind/feature, approved, cncf-cla: yes, lgtm, size/L

#1114 api: add RouteConditionReason to v1alpha2
  apis/v1alpha2/shared_types.go
  conformance/utils/kubernetes/helpers.go
Labels: kind/feature, ok-to-test, kind/api-change, approved, size/M, kind/documentation, cncf-cla: yes, lgtm, kind/deprecation

#1107 Gateway.Spec.Addresses `Extended` Support Level
  apis/v1alpha2/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/stable/gateway.networking.k8s.io_gateways.yaml
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1119 Add a "cleanup-base-resources" conformance flag, and a way to use it
  Makefile
  conformance/conformance_test.go
  conformance/utils/flags/flags.go
  conformance/utils/kubernetes/apply_test.go
  conformance/utils/suite/suite.go
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1121 Mention BackendObjectReference.Kind default in docstring
  apis/v1alpha2/object_reference_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1120 Update Traefik implementation description
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1123 Fix typos in implementations.md
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1122 Update RouteParentStatus.ControllerName Description
  apis/v1alpha2/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1118 Removing confusing part of ParentRef godoc
  apis/v1alpha2/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1126 0.4 Cherry Pick: Migrate kube-webhook-certgen to k8s.gcr.io/ingress-nginx:v1.1.1
  deploy/certificate_config.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1117 docs: add Kuma to the list of implementations
  site-src/implementations.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1129 Cleaning up PreciseHostname godocs
  apis/v1alpha2/shared_types.go
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1128 Documenting v1alpha1 deprecation, additional v1alpha1 cleanup
  site-src/concepts/api-overview.md
  site-src/faq.md
  site-src/v1alpha1/api-types/gateway.md
  site-src/v1alpha1/api-types/gatewayclass.md
  site-src/v1alpha1/api-types/httproute.md
  site-src/v1alpha1/guides/getting-started.md
  site-src/v1alpha1/guides/http-routing.md
  site-src/v1alpha1/guides/multiple-ns.md
  site-src/v1alpha1/guides/simple-gateway.md
  site-src/v1alpha1/guides/tcp.md
  site-src/v1alpha1/guides/tls.md
  site-src/v1alpha1/guides/traffic-splitting.md
  site-src/v1alpha1/references/spec.md
  site-src/v1alpha2/api-types/httproute.md
Labels: approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1066 Updating docs related to versioning and webhook
  mkdocs.yml
  site-src/concepts/guidelines.md
  site-src/concepts/versioning.md
  site-src/images/lifecycle-new-fields.png
  site-src/images/lifecycle-new-resources.png
  site-src/images/release-channel-overlap.png
  site-src/references/releases.md
  site-src/v1alpha2/contributing/devguide.md
  site-src/v1alpha2/guides/getting-started.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1134 conformance: add HTTPRoute header matching test
  conformance/tests/httproute-header-matching.go
  conformance/tests/httproute-header-matching.yaml
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L
