Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-09, with the labels that each got.

#1326 add GEP-1323: Response Header Filter
  site-src/geps/gep-1323.md
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L, kind/gep

#1296 conformance: add HTTPRoute method matching test
  conformance/tests/httproute-method-matching.go
  conformance/tests/httproute-method-matching.yaml
  conformance/utils/suite/suite.go
Labels: approved, size/M, cncf-cla: yes, lgtm, area/conformance

#1376 changed docstring in shared_types.go to account for empty strings being an error
  apis/v1alpha2/shared_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1377 Pull out the duplicate namespace definition to a separate `0-namespace.yaml` file
  config/webhook/0-namespace.yaml
  config/webhook/admission_webhook.yaml
  config/webhook/certificate_config.yaml
Labels: kind/bug, ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#1370 conformance: Add test for ensuring route match order is respected
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  conformance/tests/httproute-header-matching.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1379 Fix PYTHON_VERSION for build image
  netlify.toml
Labels: kind/bug, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm, kind/regression

#1361 Document the edge case with repeated query params
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1387 release-0.5: Cherry pick #1377 - Pull out the duplicate namespace definition to a separate 0-namespace.yaml file.
  config/webhook/0-namespace.yaml
  config/webhook/admission_webhook.yaml
  config/webhook/certificate_config.yaml
Labels: kind/bug, ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#1389 Used cached go modules for generate
  hack/update-codegen.sh
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1390 Make alpha types aliases of beta types
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/object_reference_types.go
  apis/v1alpha2/shared_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: kind/feature, approved, size/XXL, cncf-cla: yes, lgtm

#1392 Updating our versioning guidelines to allow additional types of changes
  site-src/concepts/versioning.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1393 Cherry picking several more PRs before 0.5.1 release
  apis/v1alpha2/object_reference_types.go
  apis/v1alpha2/shared_types.go
  apis/v1beta1/object_reference_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  conformance/tests/gateway-secret-missing-referenced-secret.go
  conformance/tests/gateway-secret-missing-referenced-secret.yaml
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1396 Add configurable timeout conformance test.
  conformance/tests/httproute-disallowed-kind.go
  conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
  conformance/utils/config/timeout.go
  conformance/utils/kubernetes/helpers.go
Labels: ok-to-test, approved, size/M, kind/cleanup, cncf-cla: yes, lgtm, kind/flake

#1400 Update remaining v1alpha2 references in conformance tests
  conformance/tests/gateway-unsupported-route-kind.yaml
  conformance/tests/httproute-hostname-intersection.yaml
  conformance/tests/httproute-method-matching.yaml
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#1401 Clarify HTTPRoute matching precedence
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, size/S, needs-ok-to-test, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1373 Add `ResponseHeaderModifier` to `HTTPRouteFilter`
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/validation/httproute_test.go
  apis/v1alpha2/zz_generated.deepcopy.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/validation/httproute.go
  apis/v1beta1/validation/httproute_test.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  conformance/tests/httproute-response-header-modifier.go
  conformance/tests/httproute-response-header-modifier.yaml
  conformance/utils/http/http.go
  conformance/utils/suite/suite.go
Labels: kind/feature, ok-to-test, kind/api-change, approved, cncf-cla: yes, lgtm, size/L

#1404 Fix Anchor for installing Gateway API CRD manually on Getting Started Guide
  site-src/guides/getting-started.md
Labels: size/XS, approved, needs-ok-to-test, cncf-cla: yes, lgtm

#1383 Add GEP-1364 proposal
  site-src/geps/gep-1364.md
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/gep

#1405 Marking v1alpha2 as deprecated for beta resources
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: size/XS, kind/api-change, approved, kind/cleanup, cncf-cla: yes, lgtm

#1346 HTTP rewrite matches the example text
  examples/experimental/http-redirect-rewrite/httproute-rewritepath.yaml
  site-src/guides/http-redirect-rewrite.md
Labels: ok-to-test, approved, size/S, tide/merge-method-squash, cncf-cla: yes, lgtm

#1406 Remove ReferencePolicy in favor of ReferenceGrant
  apis/v1alpha2/referencepolicy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  apis/v1alpha2/zz_generated.register.go
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  pkg/client/clientset/versioned/typed/apis/v1alpha2/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_referencepolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/referencepolicy.go
  pkg/client/informers/externalversions/apis/v1alpha2/interface.go
  pkg/client/informers/externalversions/apis/v1alpha2/referencepolicy.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apis/v1alpha2/expansion_generated.go
  pkg/client/listers/apis/v1alpha2/referencepolicy.go
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm, kind/deprecation

#1382 replace Attached condition with Accepted in HTTPRoute docs
  apis/v1alpha2/httproute_types.go
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1409 (release-0.5 cherrypick of #1382) replace Attached condition with Accepted in HTTPRoute docs
  apis/v1alpha2/httproute_types.go
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1413 website: add closing paren to GEP template
  site-src/geps/gep-696.md
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1407 Adding Changelog for v0.5.1
  CHANGELOG.md
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/webhook/admission_webhook.yaml
  hack/verify-examples-kind.sh
  pkg/generator/main.go
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1414 Bumping version to v0.5.1 throughout docs
  CHANGELOG.md
  README.md
  config/webhook/admission_webhook.yaml
  hack/verify-examples-kind.sh
  site-src/guides/getting-started.md
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm
