Repository kubernetes-sigs/gateway-api, pull requests merged in 2022-03, with the labels that each got.

#1018 Update image generation process with more consistent naming
  Makefile
  cloudbuild.yaml
  hack/build-and-push.sh
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1026 fix(conformance): manifest filenames and reading from disk
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-invalid-cross-namespace.go
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching.go
  conformance/utils/kubernetes/apply.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#1027 fix(conformance): don't use canceled context to Delete resources
  conformance/utils/kubernetes/apply.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1029 Fixing error handling and typo in roundtripper
  conformance/utils/roundtripper/roundtripper.go
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#1030 Update Implementations page with current Consul information
  site-src/implementations.md
Labels: ok-to-test, approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1034 Update image generation process with more consistent naming
  Makefile
  cloudbuild.yaml
  hack/build-and-push.sh
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1036 minor conformance test fixes
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching-across-routes.yaml
  conformance/tests/httproute-matching.go
  conformance/utils/kubernetes/helpers.go
Labels: kind/bug, ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#1043 Fix release-staging cloudbuild job - hopefully
  Makefile
  cloudbuild.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1044 Fix release-staging cloudbuild job - hopefully
  Makefile
  cloudbuild.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1045 Updating k8s references docs links to go to 1.23 instead of 1.18
  hack/api-docs/config.json
Labels: kind/bug, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1046 Adding anchor links in reference docs
  hack/api-docs/type.tpl
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1049 Correct the version mention in the Status
  README.md
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#998 fix typo of urlRewrite
  apis/v1alpha2/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  examples/v1alpha2/simple-gateway/httproute.yaml
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1051 Adding webhook to e2e tests with kind, moving deploy to gateway-system namespace
  Dockerfile
  deploy/admission_webhook.yaml
  deploy/certificate_config.yaml
  hack/invalid-examples/v1alpha2/gateway/hostname-tcp.yaml
  hack/invalid-examples/v1alpha2/gateway/hostname-udp.yaml
  hack/invalid-examples/v1alpha2/gateway/tlsconfig-tcp.yaml
  hack/invalid-examples/v1alpha2/httproute/httproute-portless-backend.yaml
  hack/invalid-examples/v1alpha2/httproute/httproute-portless-service.yaml
  hack/invalid-examples/v1alpha2/httproute/invalid-filter-duplicate.yaml
  hack/invalid-examples/v1alpha2/httproute/invalid-filter-empty.yaml
  hack/invalid-examples/v1alpha2/httproute/invalid-filter-wrong-field.yaml
  hack/verify-examples-kind.sh
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1050 Updating Security Model and Reference Policy documentation
  mkdocs.yml
  site-src/concepts/security-model.md
  site-src/v1alpha2/api-types/referencepolicy.md
  site-src/v1alpha2/images/referencepolicy-simple.png
  site-src/v1alpha2/references/cross-namespace-references.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L

#1054 Fixing broken inclusion on security model doc
  site-src/concepts/security-model.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1056 Fix a typo on website's "Implementations" page
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1057 Fixing outdated examples to use controllerName instead of controller
  site-src/v1alpha2/api-types/gatewayclass.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1064 Replacing "go get" with "go install" for kind verification
  hack/verify-examples-kind.sh
Labels: size/XS, approved, kind/failing-test, cncf-cla: yes, lgtm

#1063 Avoid creating obsolete gateway-api namespace
  deploy/certificate_config.yaml
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1065 Clarifying TLS Reencryption Docs
  site-src/concepts/api-overview.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1072 Cherry pick CI fixes into release-0.4
  hack/verify-examples-kind.sh
Labels: size/XS, approved, kind/failing-test, cncf-cla: yes, lgtm

#1069 conformance: embed manifests in Go binary
  conformance/conformance_test.go
  conformance/embed.go
  conformance/utils/kubernetes/apply.go
Labels: kind/feature, ok-to-test, approved, size/M, cncf-cla: yes, lgtm, triage/accepted

#1068 Simplify image tagging script
  hack/build-and-push.sh
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1079 Add a success message to verify-boilerplate
  hack/boilerplate/boilerplate.py
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm
