Repository kubernetes-sigs/gateway-api, pull requests merged in 2023-01, with the labels that each got.

#1622 Http rewrite conformance
  conformance/tests/httproute-rewrite-host.go
  conformance/tests/httproute-rewrite-host.yaml
  conformance/tests/httproute-rewrite-path.go
  conformance/tests/httproute-rewrite-path.yaml
  conformance/utils/http/http.go
  conformance/utils/suite/suite.go
Labels: kind/feature, ok-to-test, approved, cncf-cla: yes, lgtm, size/L, area/conformance

#1627 conformance: Add additional path matching edge cases
  conformance/tests/httproute-matching.go
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1628 fix backend name
  conformance/tests/httproute-rewrite-path.go
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm, area/conformance

#1625 Doc: SecretObjectReference use "Secret" as Kind
  apis/v1beta1/object_reference_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Labels: ok-to-test, size/XS, approved, tide/merge-method-squash, kind/documentation, cncf-cla: yes, lgtm

#1547 Add migration guide from Ingress
  examples/standard/simple-http-https/bar-route.yaml
  examples/standard/simple-http-https/foo-route.yaml
  examples/standard/simple-http-https/gateway.yaml
  examples/standard/simple-http-https/tls-redirect-route.yaml
  mkdocs.yml
  site-src/guides/index.md
  site-src/guides/migrating-from-ingress.md
Labels: ok-to-test, approved, tide/merge-method-squash, kind/documentation, cncf-cla: yes, lgtm, size/XL

#1636 upgrade python deps
  requirements.txt
Labels: ok-to-test, approved, tide/merge-method-squash, size/M, kind/cleanup, cncf-cla: yes, lgtm

#1644 update regex to comply with RFC-3986
  apis/v1beta1/validation/httproute.go
Labels: kind/bug, ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1652 Fix GEP template - status link was wrong
  site-src/geps/gep-696.md
Labels: ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1656 Fix typo around redirection
  site-src/guides/http-redirect-rewrite.md
Labels: size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1587 Issue #1579 TLSRoute Passthrough Conformance Test (normative)
  conformance/base/manifests.yaml
  conformance/conformance_test.go
  conformance/tests/tlsroute-simple-same-namespace.go
  conformance/tests/tlsroute-simple-same-namespace.yaml
  conformance/utils/config/timeout.go
  conformance/utils/http/http.go
  conformance/utils/kubernetes/certificate.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/roundtripper/roundtripper.go
  conformance/utils/suite/suite.go
  conformance/utils/tls/tls.go
  site-src/concepts/conformance.md
Labels: ok-to-test, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/L, area/conformance

#1671 reason `NoMatchingParent` added to the documentation
  apis/v1beta1/shared_types.go
  requirements.txt
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1655 Loosen `Accepted` check in GWC Obs Generation test
  conformance/tests/gatewayclass-observed-generation-bump.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/suite/suite.go
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1675 Fixing verify-boilerplate to work with latest build images
  hack/boilerplate/boilerplate.py
Labels: kind/bug, size/XS, approved, kind/failing-test, cncf-cla: yes, lgtm

#1673 Define recommended conditions for policies
  site-src/geps/gep-713.md
Labels: kind/feature, ok-to-test, approved, size/M, kind/documentation, cncf-cla: yes, lgtm, kind/gep

#1493 Mesh: define namespace boundaries for parent and backend
  site-src/geps/gep-1426.md
Labels: approved, size/M, cncf-cla: yes, lgtm, kind/gep

#1684 fix: remove ClusterRoleBinding's namespace field
  config/webhook/certificate_config.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1685 documentation: add STUNner to the list of implementations
  site-src/implementations.md
Labels: approved, size/S, needs-ok-to-test, kind/documentation, cncf-cla: yes, lgtm

#1689 Update README.md
  README.md
  RELEASE.md
Labels: documentation, size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm
