Repository kubernetes-sigs/gateway-api, pull requests merged in 2023-06, with the labels that each got.

#2081 Adding changelog for v0.7.1
  CHANGELOG.md
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  config/webhook/admission_webhook.yaml
  pkg/generator/main.go
Labels: approved, release-note-none, size/M, kind/documentation, cncf-cla: yes, lgtm

#2084 Update kustomization.yaml to include reference grant
  config/crd/kustomization.yaml
Labels: kind/bug, size/XS, approved, release-note, cncf-cla: yes, lgtm

#2069 Updating storage and served versions for beta resources
  apis/v1alpha2/gateway_types.go
  apis/v1alpha2/gatewayclass_types.go
  apis/v1alpha2/httproute_types.go
  apis/v1alpha2/referencegrant_types.go
  apis/v1beta1/referencegrant_types.go
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
Labels: size/XS, approved, release-note, kind/cleanup, cncf-cla: yes, lgtm, release-blocker

#2062 chore: conformance profiles API version and channel
  geps/gep-1709.md
Labels: approved, release-note-none, size/M, cncf-cla: yes, lgtm, kind/gep, area/conformance

#2092 apis/v1beta1: Host header must not be modified
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: size/XS, approved, release-note, kind/cleanup, cncf-cla: yes, lgtm

#2031 gamma: drop provision to omit backendRef
  geps/gep-1426.md
Labels: approved, release-note-none, size/M, cncf-cla: yes, lgtm, kind/gep

#2100 Add Knative to integrations
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm

#2105 Use correct constant for listener reason "Programmed"
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
Labels: ok-to-test, size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm, area/conformance

#2103 docs: update APISIX Ingress implementation status
  site-src/implementations.md
Labels: size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#2097 docs: add probationary step to Experimental GEP phase
  geps/gep-1016.md
  geps/gep-1323.md
  geps/gep-1748.md
  geps/gep-713.md
  geps/gep-957.md
  geps/overview.md
  site-src/concepts/conformance.md
  site-src/contributing/enhancement-requests.md
Labels: approved, kind/documentation, cncf-cla: yes, lgtm, size/L, kind/gep

#2106 conformance: use distinct resource names for test isolation
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.yaml
  conformance/tests/gateway-secret-reference-grant-specific.go
  conformance/tests/gateway-secret-reference-grant-specific.yaml
Labels: kind/bug, ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm, kind/flake, area/conformance

#2029 conformance: add MeshConsumerRoute case for GAMMA
  conformance/mesh/manifests.yaml
  conformance/tests/mesh-consumer-route.go
  conformance/tests/mesh-consumer-route.yaml
  conformance/utils/echo/pod.go
  conformance/utils/suite/suite.go
Labels: approved, release-note-none, cncf-cla: yes, lgtm, size/L, area/conformance, kind/test

#2115 Add Conformance Details section to GEP template
  geps/gep-696.md
Labels: size/XS, approved, release-note, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm, area/conformance

#2079 Clarify docstring for ReplacePrefixMatch.
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: ok-to-test, approved, size/S, release-note-none, kind/documentation, cncf-cla: yes, lgtm, area/conformance

#2116 conformance: Ignore state of terminating pods
  conformance/utils/kubernetes/helpers.go
Labels: kind/bug, size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm, kind/flake, area/conformance, kind/test

#2119 live update site when geps are changed
  hack/make-docs.sh
  hack/mkdocs-copy-geps.py
  mkdocs.yml
Labels: approved, release-note-none, size/M, cncf-cla: yes, lgtm

#2120 use go1.20
  docker/Dockerfile.webhook
Labels: ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm

#2121 Add LiorLieberman to conformance reviewers
  OWNERS_ALIASES
Labels: size/XS, approved, release-note-none, cncf-cla: yes, lgtm, area/conformance

#2132 Move GEP-1282 to declined
  geps/gep-1282.md
  mkdocs.yml
Labels: approved, size/S, release-note, kind/cleanup, cncf-cla: yes, lgtm, kind/gep

#2114 Add missing geps to mkdocs
  mkdocs.yml
Labels: ok-to-test, size/XS, approved, release-note, cncf-cla: yes, lgtm

#2135 add Flynn as GAMMA lead, remove Mike Morris
  OWNERS_ALIASES
Labels: approved, size/S, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#2138 ci(linter): enable several linters
  .golangci.yml
  apis/v1alpha2/validation/common.go
  apis/v1beta1/validation/common.go
  apis/v1beta1/validation/common_test.go
  conformance/tests/gateway-modify-listeners.go
  conformance/tests/gateway-observed-generation-bump.go
  conformance/tests/gateway-with-attached-routes.go
  conformance/tests/httproute-invalid-backendref-nonexistent.go
  conformance/tests/httproute-invalid-backendref-unknown-kind.go
  conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
  conformance/tests/httproute-partially-invalid-via-reference-grant.go
  conformance/tests/httproute-path-match-order.go
  conformance/tests/httproute-redirect-host-and-status.go
  conformance/tests/httproute-redirect-path.go
  conformance/tests/httproute-redirect-port-and-scheme.go
  conformance/tests/httproute-redirect-port.go
  conformance/tests/httproute-redirect-scheme.go
  conformance/utils/http/http.go
  conformance/utils/http/mirror.go
  conformance/utils/kubernetes/certificate.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/suite/suite.go
  pkg/admission/server.go
Labels: ok-to-test, approved, release-note-none, cncf-cla: yes, lgtm, size/XL

#2117 Edit Nginx timeouts diagram to match Envoy's in gep-1742.md
  geps/gep-1742.md
Labels: ok-to-test, approved, size/S, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#2101 Add conformance tests with requestHeaderModifier
  conformance/tests/httproute-request-mirror.go
  conformance/tests/httproute-request-mirror.yaml
  conformance/tests/httproute-response-header-modifier.go
  conformance/tests/httproute-response-header-modifier.yaml
  conformance/tests/httproute-rewrite-host.go
  conformance/tests/httproute-rewrite-host.yaml
  conformance/tests/httproute-rewrite-path.go
  conformance/tests/httproute-rewrite-path.yaml
Labels: ok-to-test, approved, tide/merge-method-squash, release-note-none, cncf-cla: yes, lgtm, size/L, area/conformance, kind/test

#2143 Conformance - Fix Makefile
  Makefile
Labels: ok-to-test, size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm, area/conformance

#1997 GEP-1742: HTTPRoute Timeouts API
  geps/gep-1742.md
  mkdocs.yml
Labels: ok-to-test, approved, tide/merge-method-squash, release-note-none, cncf-cla: yes, lgtm, size/L, kind/gep

#2156 Fixing broken presubmits by bumping base image version
  docker/Dockerfile.webhook
Labels: kind/bug, size/XS, approved, release-note-none, cncf-cla: yes, lgtm

#2149 Fix typo GatewaReason -> GatewayReason
  apis/v1beta1/gateway_types.go
Labels: ok-to-test, size/XS, approved, release-note, kind/cleanup, cncf-cla: yes, lgtm

#2076 conformance against invalid ReferenceGrants in HTTPRoute and TLSRoute
  conformance/base/manifests.yaml
  conformance/tests/httproute-invalid-reference-grant.go
  conformance/tests/httproute-invalid-reference-grant.yaml
  conformance/tests/tlsroute-invalid-reference-grant.go
  conformance/tests/tlsroute-invalid-reference-grant.yaml
  conformance/utils/config/timeout.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/suite/experimental_suite.go
  conformance/utils/suite/suite.go
Labels: ok-to-test, approved, release-note, cncf-cla: yes, lgtm, size/L, area/conformance, kind/test

#2158 Add missing '`' in policy-attachment.md
  site-src/references/policy-attachment.md
Labels: ok-to-test, size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm
