Repository kubernetes-sigs/gateway-api, pull requests merged in 2023-02, with the labels that each got.

#1672 Add condition in Failed accepted reasons
  apis/v1beta1/shared_types.go
Labels: ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1693 fix(docs): SecretObjectReference to HTTPPathMatch
  site-src/guides/migrating-from-ingress.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1692 Fix SupportedKinds check
  conformance/utils/kubernetes/helpers.go
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm

#1695 Validate admission Kind first for efficiency
  pkg/admission/server.go
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1694 `ParentRefNotPermitted` route reason in conformance test
  conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
Labels: kind/feature, approved, size/S, cncf-cla: yes, lgtm

#1682 Define recommended conditions for policies
  apis/v1alpha2/policy_types.go
Labels: kind/feature, ok-to-test, approved, size/M, cncf-cla: yes, lgtm, kind/gep

#1642 Add `all-features` flag to add ability to enable all supported feature conformance tests.
  conformance/conformance_test.go
  conformance/utils/flags/flags.go
  conformance/utils/suite/suite.go
Labels: kind/feature, approved, size/M, cncf-cla: yes, lgtm

#1654 Drop obsolete sentence about `hostname.match`
  site-src/guides/tls.md
Labels: size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1704 Remove ParentRefNotPermitted
  apis/v1beta1/shared_types.go
  conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm, area/conformance

#1707 Add explicit equality checks for SupportedKinds
  conformance/utils/kubernetes/helpers.go
  conformance/utils/kubernetes/helpers_test.go
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#1710 add additional unit test case for #1703
  conformance/utils/kubernetes/helpers_test.go
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1702 release v0.6.1
  CHANGELOG.md
  RELEASE.md
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  config/webhook/admission_webhook.yaml
  hack/verify-examples-kind.sh
  pkg/generator/main.go
Labels: approved, size/M, kind/documentation, cncf-cla: yes, lgtm

#1712 conformance: require `SupportTLSRoute` feature for `TLSRoute` test
  conformance/tests/tlsroute-simple-same-namespace.go
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1717 v0.6.1 updates
  CHANGELOG.md
  README.md
  RELEASE.md
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  config/webhook/admission_webhook.yaml
  hack/verify-examples-kind.sh
  pkg/generator/main.go
Labels: approved, kind/cleanup, cncf-cla: yes, lgtm, size/L

#1714 conformance: check reason in HTTPRouteInvalidCrossNamespaceParentRef test
  conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
Labels: approved, size/S, cncf-cla: yes, lgtm, area/conformance

#1724 cleanup: GEP-1324 Typo - Fix indentation
  site-src/geps/gep-1324.md
Labels: ok-to-test, size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1730 test: add not matching sectioName test
  conformance/tests/httproute-invalid-parentref-not-matching-section-name.go
  conformance/tests/httproute-invalid-parentref-not-matching-section-name.yaml
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1733 Improving PR and Issue templates for Conformance Tests
  .github/ISSUE_TEMPLATE/conformance.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1736 chore: replace usage of the deprecated k8s.gcr.io registry
  config/webhook/certificate_config.yaml
Labels: size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1732 Requiring "Programmed" condition in conformance tests
  conformance/tests/gateway-observed-generation-bump.go
  conformance/tests/httproute-disallowed-kind.go
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-observed-generation-bump.go
  conformance/utils/config/timeout.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/suite/suite.go
Labels: priority/important-soon, approved, size/M, cncf-cla: yes, lgtm, area/conformance, kind/test

#1737 doc: correct conformance-test (internal) function documentation
  conformance/conformance_test.go
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm, area/conformance

#1726 unit test for listenersMatch in conformance utils
  conformance/utils/kubernetes/helpers_test.go
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm

#1701 Gateway default conditions updated
  apis/v1beta1/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1738 Small unit test bump
  Makefile
  conformance/utils/kubernetes/helpers_test.go
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L, kind/test

#1739 docs: add goals and intro for conformane profiles GEP
  site-src/geps/gep-1709.md
Labels: approved, size/M, cncf-cla: yes, lgtm, kind/gep, area/conformance

#1747 docs: fix api-overview.md typo
  site-src/concepts/api-overview.md
Labels: approved, size/S, needs-ok-to-test, kind/documentation, cncf-cla: yes, lgtm

#1752 Update version links in guide
  RELEASE.md
  site-src/guides/index.md
Labels: ok-to-test, size/XS, approved, cncf-cla: yes, lgtm

#1753 drop default method matches from GRPCRoute
  apis/v1alpha2/grpcroute_types.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
Labels: kind/bug, size/XS, approved, cncf-cla: yes, lgtm

#1756 Moving GEPs to separate directory for separate reviewers and approvers
  .gitignore
  geps/OWNERS
  geps/gep-1016.md
  geps/gep-1282.md
  geps/gep-1323.md
  geps/gep-1324.md
  geps/gep-1364.md
  geps/gep-1426.md
  geps/gep-1709.md
  geps/gep-696.md
  geps/gep-709.md
  geps/gep-713.md
  geps/gep-718.md
  geps/gep-724.md
  geps/gep-726.md
  geps/gep-735.md
  geps/gep-746.md
  geps/gep-820.md
  geps/gep-851.md
  geps/gep-917.md
  geps/gep-922.md
  geps/gep-957.md
  geps/images/1324-backend-ref.png
  geps/images/1324-decomposed-view-of-service.png
  geps/images/1324-resource-view-of-service.png
  geps/images/1324-service-frontend.png
  geps/images/709-inline.png
  geps/images/709-referencegrant.png
  geps/images/713-hierarchy.png
  geps/images/713-ingress-attachment.png
  geps/images/713-ingress-complex.png
  geps/images/713-ingress-simple.png
  geps/images/713-mesh-complex.png
  geps/images/713-mesh-simple.png
  geps/images/713-policy-hierarchy.png
  geps/images/713-servicebinding-complex.png
  geps/images/713-servicebinding-simple.png
  geps/images/724-alt1.png
  geps/images/724-alt2.png
  geps/images/724-proposal.png
  geps/overview.md
  hack/make-docs.sh
  site-src/OWNERS
Labels: approved, size/S, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1750 fix: Deprecation of package ioutil in Go 1.16
  .golangci.yml
  conformance/utils/roundtripper/roundtripper.go
Labels: approved, size/S, needs-ok-to-test, cncf-cla: yes, lgtm, kind/deprecation

#1761 Log Generation / Observed generation.
  conformance/utils/kubernetes/helpers.go
  conformance/utils/kubernetes/helpers_test.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm, area/conformance
