Repository kubernetes-sigs/gateway-api, pull requests merged in 2023-04, with the labels that each got.

#1894 Conformance Tests: No implicit test runs without features
  conformance/conformance_test.go
  conformance/tests/gateway-invalid-route-kind.go
  conformance/tests/gateway-invalid-tls-certificateref.go
  conformance/tests/gateway-modify-listeners.go
  conformance/tests/gateway-observed-generation-bump.go
  conformance/tests/gateway-secret-invalid-reference-grant.go
  conformance/tests/gateway-secret-missing-reference-grant.go
  conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
  conformance/tests/gateway-secret-reference-grant-specific.go
  conformance/tests/gateway-with-attached-routes.go
  conformance/tests/gatewayclass-observed-generation-bump.go
  conformance/tests/httproute-cross-namespace.go
  conformance/tests/httproute-disallowed-kind.go
  conformance/tests/httproute-exact-path-matching.go
  conformance/tests/httproute-header-matching.go
  conformance/tests/httproute-hostname-intersection.go
  conformance/tests/httproute-invalid-backendref-nonexistent.go
  conformance/tests/httproute-invalid-backendref-unknown-kind.go
  conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
  conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
  conformance/tests/httproute-invalid-parentref-not-matching-section-name.go
  conformance/tests/httproute-listener-hostname-matching.go
  conformance/tests/httproute-matching-across-routes.go
  conformance/tests/httproute-matching.go
  conformance/tests/httproute-method-matching.go
  conformance/tests/httproute-observed-generation-bump.go
  conformance/tests/httproute-partially-invalid-via-reference-grant.go
  conformance/tests/httproute-path-match-order.go
  conformance/tests/httproute-query-param-matching.go
  conformance/tests/httproute-redirect-host-and-status.go
  conformance/tests/httproute-redirect-path.go
  conformance/tests/httproute-redirect-port.go
  conformance/tests/httproute-redirect-scheme.go
  conformance/tests/httproute-reference-grant.go
  conformance/tests/httproute-request-header-modifier.go
  conformance/tests/httproute-response-header-modifier.go
  conformance/tests/httproute-rewrite-host.go
  conformance/tests/httproute-rewrite-path.go
  conformance/tests/httproute-simple-same-namespace.go
  conformance/tests/main.go
  conformance/tests/mesh-basic.go
  conformance/tests/mesh-split.go
  conformance/tests/tlsroute-simple-same-namespace.go
  conformance/utils/suite/features.go
  conformance/utils/suite/suite.go
  site-src/concepts/conformance.md
Labels: ok-to-test, approved, kind/cleanup, cncf-cla: yes, lgtm, size/L, area/conformance, kind/test, release-blocker

#1879 Configure and document image promotion process
  RELEASE.md
  hack/update-webhook-yaml.sh
Labels: ok-to-test, approved, size/M, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1905 Graduating GEP-1323: Response Header Modifier to standard
  apis/v1alpha2/grpcroute_types.go
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: kind/feature, size/XS, approved, cncf-cla: yes, lgtm

#1908 Clarifying Port Redirect Behavior
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1914 Fix mermaid diagram rendering
  geps/overview.md
Labels: size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1915 Fix GEP link
  geps/overview.md
Labels: size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1910 `BackendRefs` fixed in `HTTPRoute` conformance tests
  conformance/tests/gateway-modify-listeners.yaml
  conformance/tests/gateway-with-attached-routes.yaml
Labels: kind/bug, approved, size/S, cncf-cla: yes, lgtm

#1916 doc: Add Amazon EKS to the list of implementations
  site-src/implementations.md
Labels: ok-to-test, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1917 Loosen requirement for GC finalizer
  apis/v1alpha2/gatewayclass_types.go
  apis/v1beta1/gatewayclass_types.go
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
Labels: size/XS, approved, priority/important-longterm, kind/documentation, cncf-cla: yes, lgtm

#1921 docs: fix broken link for EKS
  site-src/implementations.md
Labels: size/XS, approved, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#1457 Webhook: validate the combination of port, protocol, and hostname are unique for each listener.
  apis/v1beta1/validation/gateway.go
  apis/v1beta1/validation/gateway_test.go
Labels: kind/feature, ok-to-test, approved, tide/merge-method-squash, cncf-cla: yes, lgtm, size/L

#1843 Adding GEP-1748: Gateway API Interaction with Multi-Cluster Services
  examples/standard/multicluster/0-namespaces.yaml
  examples/standard/multicluster/httproute-gamma.yaml
  examples/standard/multicluster/httproute-hybrid.yaml
  examples/standard/multicluster/httproute-location.yaml
  examples/standard/multicluster/httproute-method.yaml
  examples/standard/multicluster/httproute-referencegrant.yaml
  examples/standard/multicluster/httproute-simple.yaml
  geps/gep-1748.md
  mkdocs.yml
Labels: approved, cncf-cla: yes, lgtm, size/L, kind/gep

#1899 make embed.FS configurable
  conformance/utils/kubernetes/apply.go
  conformance/utils/suite/suite.go
Labels: ok-to-test, approved, size/S, cncf-cla: yes, lgtm, area/conformance, kind/test

#1922 Marking ServiceImport as Extended support
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/tcproute_types.go
  apis/v1alpha2/tlsroute_types.go
  apis/v1alpha2/udproute_types.go
  apis/v1beta1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Labels: kind/feature, approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1924 Fix a minor typo in index.md.
  site-src/index.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1931 Update multiple-ns.md
  site-src/guides/multiple-ns.md
Labels: ok-to-test, size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1933 cleanup: Replace error types when validating unique fields
  apis/v1beta1/validation/gateway.go
Labels: ok-to-test, size/XS, approved, kind/cleanup, cncf-cla: yes, lgtm

#1934 cleanup: Touch up some of the doc comments
  apis/v1beta1/gateway_types.go
  apis/v1beta1/httproute_types.go
Labels: ok-to-test, approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1946 Change Custom to Implementation-specific in Httproute api types docs.
  site-src/api-types/httproute.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1952 Fix wrong grpc link in guides docs.
  site-src/guides/index.md
Labels: size/XS, approved, kind/documentation, cncf-cla: yes, lgtm

#1949 Fixes to allow the mesh feature to be tested, including alone
  conformance/conformance_test.go
  conformance/utils/flags/flags.go
  conformance/utils/suite/suite.go
  site-src/concepts/conformance.md
Labels: ok-to-test, approved, size/M, cncf-cla: yes, lgtm, area/conformance, kind/test

#1969 Documenting HTTP header modifiers
  examples/experimental/http-response-header.yaml
  examples/standard/http-request-header-add.yaml
  examples/standard/http-request-header-remove.yaml
  examples/standard/http-request-header-set.yaml
  mkdocs.yml
  site-src/guides/http-header-modifier.md
Labels: ok-to-test, approved, cncf-cla: yes, lgtm, size/L

#1918 cleanup: Add String() function for roundtripper.Request
  conformance/utils/roundtripper/roundtripper.go
Labels: ok-to-test, approved, size/S, kind/cleanup, cncf-cla: yes, lgtm

#1978 Update Envoy Gateway support in #implementations
  site-src/implementations.md
Labels: approved, size/S, kind/documentation, cncf-cla: yes, lgtm

#1972 Validation cleanup from v0.7.0 API Review
  apis/v1alpha2/validation/grpcroute.go
  apis/v1beta1/validation/gateway.go
Labels: approved, size/M, kind/cleanup, cncf-cla: yes, lgtm
