Repository kubernetes-sigs/gateway-api, pull requests merged in 2023-10, with the labels that each got.

#2426 conformance: Add v0.8.1 conformance report for Cilium
  conformance/reports/v0.8.1/cilium-cilium.yaml
  site-src/implementations.md
Labels: ok-to-test, approved, release-note-none, size/M, kind/documentation, cncf-cla: yes, lgtm

#2393 Update the contributing page about the GEP process
  site-src/contributing/enhancement-requests.md
Labels: approved, release-note-none, size/M, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#2444 [GEP-1911] Update BackendRef with GEP details
  apis/v1alpha2/grpcroute_types.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/shared_types.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  geps/gep-1911.md
  pkg/generator/main.go
Labels: approved, tide/merge-method-squash, release-note-none, size/M, kind/documentation, cncf-cla: yes, lgtm, kind/gep

#2447 Add conformance echo-server code and image build (echo-basic)
  Makefile
  conformance/echo-basic/echo-basic.go
  conformance/echo-basic/echo-basic_test.go
  conformance/echo-basic/go.mod
  docker/Dockerfile.echo-advanced
  docker/Dockerfile.echo-basic
  go.work
  go.work.sum
  hack/build-and-push.sh
Labels: ok-to-test, approved, release-note, tide/merge-method-squash, cncf-cla: yes, lgtm, size/XL, area/conformance, kind/test

#2443 Check gateway positive-polarity conditions
  conformance/utils/kubernetes/helpers.go
Labels: approved, release-note-none, size/M, cncf-cla: yes, lgtm, area/conformance, kind/test, release-blocker

#2429 Adding new PartiallyInvalid condition for Routes
  apis/v1beta1/shared_types.go
Labels: kind/feature, approved, release-note, size/M, cncf-cla: yes, lgtm, release-blocker

#2461 Supported features implementation
  apis/v1beta1/gatewayclass_types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
  conformance/tests/httproute-response-header-modifier.go
  conformance/tests/mesh-consumer-route.go
  conformance/tests/mesh-frontend-hostname.go
  conformance/tests/mesh-frontend.go
  conformance/tests/mesh-ports.go
  conformance/utils/suite/features.go
Labels: kind/feature, approved, release-note, size/M, cncf-cla: yes, lgtm

#2465 Documenting Listener Isolation in Gateway Spec
  apis/v1beta1/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Labels: size/XS, approved, release-note, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#2421 Update WSO2 APK implementation status in docs
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#2412 Conformance tests for static Gateway addresses
  CHANGELOG.md
  apis/v1beta1/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  conformance/tests/gateway-static-addresses.go
  conformance/tests/gateway-static-addresses.yaml
  conformance/utils/config/timeout.go
  conformance/utils/kubernetes/apply.go
  conformance/utils/kubernetes/helpers.go
  conformance/utils/suite/experimental_suite.go
  conformance/utils/suite/features.go
  conformance/utils/suite/suite.go
Labels: ok-to-test, approved, tide/merge-method-squash, release-note-none, cncf-cla: yes, lgtm, size/XL, area/conformance, kind/test, release-blocker

#2467 Adding venv for verify-yamllint
  hack/verify-yamllint.sh
Labels: ok-to-test, size/XS, approved, kind/failing-test, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#2454 Add implementer's guide
  mkdocs.yml
  site-src/concepts/guidelines.md
  site-src/references/implementers-guide.md
  site-src/references/spec.md
Labels: approved, release-note, kind/documentation, cncf-cla: yes, lgtm, size/L

#2470 Fix mkdocs.yml :facepalm:
  mkdocs.yml
Labels: size/XS, approved, release-note-none, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm

#2468 Adding new images for conformance tests
  conformance/base/manifests.yaml
  conformance/mesh/manifests.yaml
Labels: approved, size/S, release-note-none, kind/cleanup, cncf-cla: yes, lgtm, area/conformance

#2436 Add distinct concept to Listener definition
  apis/v1beta1/gateway_types.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Labels: approved, release-note, kind/cleanup, cncf-cla: yes, lgtm, size/L, area/conformance

#2448 Update GEP-713 and add BackendTLSPolicy implementation
  apis/v1alpha2/backendtlspolicy_types.go
  apis/v1alpha2/policy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  apis/v1alpha2/zz_generated.register.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/object_reference_types.go
  apis/v1beta1/shared_types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  geps/gep-1897.md
  geps/gep-713.md
  mkdocs.yml
  pkg/client/clientset/versioned/typed/apis/v1alpha2/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/backendtlspolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_backendtlspolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/generated_expansion.go
  pkg/client/informers/externalversions/apis/v1alpha2/backendtlspolicy.go
  pkg/client/informers/externalversions/apis/v1alpha2/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apis/v1alpha2/backendtlspolicy.go
  pkg/client/listers/apis/v1alpha2/expansion_generated.go
Labels: kind/feature, approved, release-note, cncf-cla: yes, lgtm, size/L, kind/gep

#2474 Add policy label to BackendTLSPolicy to make it recognizable in gwctl
  apis/v1alpha2/backendtlspolicy_types.go
  config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#2472 add h2c server to echo-basic
  conformance/echo-basic/echo-basic.go
  conformance/echo-basic/go.mod
  conformance/echo-basic/go.sum
  go.work.sum
Labels: approved, release-note-none, size/M, cncf-cla: yes, lgtm

#2428 Add gwctl to gateway-api repo
  Makefile
  go.work
  go.work.sum
  gwctl/README.md
  gwctl/cmd/main.go
  gwctl/go.mod
  gwctl/go.sum
  gwctl/pkg/cmd/describe/describe.go
  gwctl/pkg/cmd/get/get.go
  gwctl/pkg/cmd/utils/printer/backends.go
  gwctl/pkg/cmd/utils/printer/gatewayclasses.go
  gwctl/pkg/cmd/utils/printer/gatewayclasses_test.go
  gwctl/pkg/cmd/utils/printer/gateways.go
  gwctl/pkg/cmd/utils/printer/gateways_test.go
  gwctl/pkg/cmd/utils/printer/httproutes.go
  gwctl/pkg/cmd/utils/printer/httproutes_test.go
  gwctl/pkg/cmd/utils/printer/policies.go
  gwctl/pkg/cmd/utils/printer/policies_test.go
  gwctl/pkg/cmd/utils/types.go
  gwctl/pkg/common/clients.go
  gwctl/pkg/common/resourcehelpers/backends.go
  gwctl/pkg/common/resourcehelpers/gatewayclasses.go
  gwctl/pkg/common/resourcehelpers/gateways.go
  gwctl/pkg/common/resourcehelpers/httproutes.go
  gwctl/pkg/common/testhelpers.go
  gwctl/pkg/effectivepolicy/backends.go
  gwctl/pkg/effectivepolicy/effectivepolicy.go
  gwctl/pkg/effectivepolicy/gatewayclasses.go
  gwctl/pkg/effectivepolicy/gateways.go
  gwctl/pkg/effectivepolicy/httproutes.go
  gwctl/pkg/effectivepolicy/namespaces.go
  gwctl/pkg/policymanager/helpers.go
  gwctl/pkg/policymanager/manager.go
  gwctl/pkg/policymanager/merger.go
  gwctl/pkg/policymanager/merger_test.go
Labels: kind/feature, approved, size/XXL, release-note, cncf-cla: yes, lgtm

#2478 Checkout go.work and go.work.sum from the repository
  .gitignore
  Makefile
  go.work
  go.work.sum
Labels: approved, size/S, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#2481 conformance: use echo-advanced in Mesh tests, echo-basic no longer has a client
  conformance/mesh/manifests.yaml
Labels: kind/bug, size/XS, approved, release-note-none, cncf-cla: yes, lgtm, area/conformance

#2476 Cleanup related to v1.0.0 review
  apis/v1alpha2/backendtlspolicy_types.go
  apis/v1alpha2/grpcroute_types.go
  apis/v1alpha2/policy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  apis/v1beta1/gatewayclass_types.go
  apis/v1beta1/httproute_types.go
  apis/v1beta1/object_reference_types.go
  apis/v1beta1/shared_types.go
  apis/v1beta1/zz_generated.deepcopy.go
  config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  hack/supportedfeatures/main.go
Labels: approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm, size/L

#2451 Add option to run single conformance test for test dev/debug
  conformance/conformance_test.go
  conformance/utils/flags/flags.go
  conformance/utils/suite/suite.go
Labels: ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm, area/conformance, kind/test

#2484 dependabot: group k8s.io golang dependencies
  .github/dependabot.yml
Labels: ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm

#2254 Route timeout conformance tests
  conformance/tests/httproute-timeout-backend-request.go
  conformance/tests/httproute-timeout-backend-request.yaml
  conformance/tests/httproute-timeout-request.go
  conformance/tests/httproute-timeout-request.yaml
  conformance/utils/http/http.go
  conformance/utils/roundtripper/roundtripper.go
  conformance/utils/suite/features.go
Labels: ok-to-test, approved, tide/merge-method-squash, release-note-none, cncf-cla: yes, lgtm, size/L, area/conformance, kind/test

#2489 Fix timeouts conformance tests
  conformance/tests/httproute-timeout-backend-request.go
  conformance/tests/httproute-timeout-request.go
Labels: kind/bug, approved, size/S, release-note-none, cncf-cla: yes, lgtm

#2479 Include make target for bumping echo-basic & advanced in our conformance files
  Makefile
  conformance/base/manifests.yaml
  conformance/mesh/manifests.yaml
  hack/update-conformance-image-refs.sh
Labels: approved, release-note, size/M, kind/cleanup, cncf-cla: yes, lgtm, area/conformance, kind/test

#2482 Adding changelog for v1.0.0-rc1
  CHANGELOG.md
  config/webhook/admission_webhook.yaml
Labels: approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm, size/L

#2494 conformance: revert ver to v1beta1 for RefGrant
  conformance/tests/gateway-secret-invalid-reference-grant.yaml
Labels: approved, size/S, release-note, cncf-cla: yes, lgtm

#2498 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, approved, tide/merge-method-squash, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#2491 BackendTLSPolicy cel tests
  apis/v1alpha2/backendtlspolicy_types.go
  config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
  pkg/test/cel/backendtlspolicy_test.go
Labels: ok-to-test, approved, release-note-none, cncf-cla: yes, lgtm, size/L, kind/test

#2510 Adds +optional Marker to GatewayInfrastructure Fields
  apis/v1/gateway_types.go
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#2471 Docs: Renamed References to Reference in site-src
  README.md
  apis/v1alpha2/validation/gateway.go
  apis/v1alpha2/validation/gatewayclass.go
  apis/v1alpha2/validation/grpcroute.go
  apis/v1alpha2/validation/httproute.go
  apis/v1alpha2/validation/tcproute.go
  apis/v1alpha2/validation/tlsroute.go
  apis/v1alpha2/validation/udproute.go
  apis/v1beta1/validation/gateway.go
  apis/v1beta1/validation/gatewayclass.go
  apis/v1beta1/validation/httproute.go
  geps/gep-1323.md
  geps/gep-1364.md
  geps/gep-1426.md
  geps/gep-1619.md
  geps/gep-1867.md
  geps/gep-1897.md
  hack/make-docs.sh
  mkdocs.yml
  site-src/api-types/gatewayclass.md
  site-src/api-types/grpcroute.md
  site-src/api-types/httproute.md
  site-src/api-types/referencegrant.md
  site-src/faq.md
  site-src/guides/grpc-routing.md
  site-src/guides/http-redirect-rewrite.md
  site-src/guides/http-routing.md
  site-src/guides/migrating-from-ingress.md
  site-src/guides/multiple-ns.md
  site-src/guides/tcp.md
  site-src/guides/traffic-splitting.md
  site-src/index.md
  site-src/reference/images/policy-hierarchy.png
  site-src/reference/images/referencepolicy.png
  site-src/reference/implementers-guide.md
  site-src/reference/policy-attachment.md
  site-src/reference/spec.md
  site-src/v1alpha2/reference
  site-src/v1alpha2/references
Labels: ok-to-test, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm, size/L

#2496 Updating conformance images will now respect REGISTRY env var
  hack/update-conformance-image-refs.sh
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm, area/conformance, kind/test

#2511 add v1 to various client schemes
  conformance/conformance_test.go
  conformance/experimental_conformance_test.go
  gwctl/pkg/common/clients.go
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm, area/conformance, kind/test

#2456 [GEP-1911] h2c backend protocol conformance
  conformance/base/manifests.yaml
  conformance/tests/httproute-backend-protocol-h2c.go
  conformance/tests/httproute-backend-protocol-h2c.yaml
  conformance/utils/http/http.go
  conformance/utils/roundtripper/roundtripper.go
  conformance/utils/suite/features.go
Labels: approved, release-note-none, cncf-cla: yes, lgtm, size/L, area/conformance, kind/test

#2495 [GEP-1911] websocket backend protocol conformance
  conformance/base/manifests.yaml
  conformance/echo-basic/echo-basic.go
  conformance/tests/httproute-backend-protocol-ws.go
  conformance/tests/httproute-backend-protocol-ws.yaml
  conformance/utils/suite/features.go
Labels: approved, release-note-none, cncf-cla: yes, lgtm, size/L, area/conformance, kind/test

#2519 Fix many broken links in GEP-1911
  geps/gep-1911.md
Labels: approved, size/S, release-note-none, cncf-cla: yes, lgtm

#2521 bump images to latest ref
  conformance/base/manifests.yaml
  conformance/mesh/manifests.yaml
Labels: approved, size/S, release-note-none, kind/cleanup, cncf-cla: yes, lgtm, area/conformance

#2522 Mark GEP-1911 as Experimental
  geps/gep-1911.md
  mkdocs.yml
Labels: size/XS, approved, release-note-none, cncf-cla: yes, lgtm, kind/gep

#2477 Conformance: Adds Test to Exercise Gateway AttachedRoutes
  conformance/tests/gateway-with-attached-routes.go
  conformance/tests/gateway-with-attached-routes.yaml
Labels: approved, release-note-none, size/M, cncf-cla: yes, lgtm, area/conformance, kind/test

#2515 implement exemptFeatures for conformance profile
  conformance/utils/suite/experimental_suite.go
Labels: size/XS, approved, release-note, cncf-cla: yes, lgtm

#2523 Adding changelog for v1.0.0-rc2
  CHANGELOG.md
  config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  pkg/generator/main.go
Labels: approved, size/S, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#2517 update steps to try it out for gwctl
  gwctl/README.md
Labels: ok-to-test, size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#2516 Add Easegress implementation
  site-src/implementations.md
Labels: ok-to-test, approved, size/S, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#2529 Add kind/gep owner label for geps files
  geps/OWNERS
Labels: ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm

#2525 Update implementations.md: Cilium is now CNCF Graduates Project
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#2514 Update conformance report for NGINX Gateway Fabric
  conformance/reports/v0.8.1/nginxinc-nginx-gateway-fabric.yaml
  site-src/implementations.md
Labels: ok-to-test, approved, release-note-none, size/M, cncf-cla: yes, lgtm, area/conformance

#2492 HTTPRoute Timeouts documentation
  examples/experimental/http-route-timeouts/timeout-example.yaml
  site-src/api-types/httproute.md
Labels: approved, release-note, tide/merge-method-squash, size/M, kind/documentation, cncf-cla: yes, lgtm

#2493 Add documentation for BackendTLSPolicy
  examples/experimental/v1alpha2/backendtlspolicy-ca-certs.yaml
  examples/experimental/v1alpha2/backendtlspolicy-system-certs.yaml
  site-src/guides/tls.md
Labels: approved, release-note, kind/documentation, cncf-cla: yes, lgtm, size/L

#2532 don't hardcode go version in update codegen script
  hack/update-codegen.sh
Labels: size/XS, approved, release-note-none, cncf-cla: yes, lgtm

#2534 Marking SupportedVersion as experimental
  apis/v1/gatewayclass_types.go
Labels: size/XS, approved, release-note, kind/documentation, cncf-cla: yes, lgtm

#2520 include a section for backend protocol in the website
  mkdocs.yml
  site-src/api-types/httproute.md
  site-src/guides/backend-protocol.md
Labels: approved, release-note-none, size/M, kind/documentation, cncf-cla: yes, lgtm, kind/gep

#2535 Fix bugs in GatewayWithAttachedRoutes
  conformance/tests/gateway-with-attached-routes.go
Labels: size/XS, approved, release-note, cncf-cla: yes, lgtm

#2546 Create v1 changelog
  CHANGELOG.md
  README.md
  config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  pkg/generator/main.go
  site-src/guides/index.md
Labels: approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm, size/L

#2533 v1.0 docs
  examples/experimental/http-route-timeouts/timeout-example.yaml
  examples/experimental/v1alpha2/backendtlspolicy-ca-certs.yaml
  examples/experimental/v1alpha2/backendtlspolicy-system-certs.yaml
  mkdocs.yml
  site-src/api-types/httproute.md
  site-src/guides/backend-protocol.md
  site-src/guides/tls.md
Labels: approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm, size/L

#2551 Bumping webhook install version
  config/webhook/admission_webhook.yaml
Labels: kind/feature, size/XS, approved, release-note-none, cncf-cla: yes, lgtm
