Repository kubernetes-sigs/gateway-api, pull requests merged in 2025-03, with the labels that each got.

#3652 sort api versions when updating clientset
  hack/update-clientset.sh
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#3638 Promote GEP 3171 - Percentage Based Request mirroring to standard
  apis/v1/grpcroute_types.go
  apis/v1/httproute_types.go
  config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  geps/gep-3171/index.md
  geps/gep-3171/metadata.yaml
  mkdocs.yml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: approved, size/S, release-note, kind/cleanup, kind/documentation, cncf-cla: yes, lgtm, kind/gep

#3596 Update Avi Kubernetes Operator (AKO) versions in the list of Gateway API implementations
  site-src/implementations.md
Labels: ok-to-test, approved, size/S, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#3607 GEP 3388 Retry Budget API Implementation
  apisx/v1alpha1/backendtrafficpolicy_types.go
  apisx/v1alpha1/shared_types.go
  apisx/v1alpha1/zz_generated.deepcopy.go
  apisx/v1alpha1/zz_generated.register.go
  applyconfiguration/apisx/v1alpha1/backendtrafficpolicy.go
  applyconfiguration/apisx/v1alpha1/backendtrafficpolicyspec.go
  applyconfiguration/apisx/v1alpha1/requestrate.go
  applyconfiguration/apisx/v1alpha1/retryconstraint.go
  applyconfiguration/internal/internal.go
  applyconfiguration/utils.go
  config/crd/experimental/gateway.networking.k8s.io_backendtrafficpolicies.yaml
  config/crd/experimental/gateway.networking.x-k8s.io_backendtrafficpolicies.yaml
  geps/gep-3388/index.md
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/apisx_client.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/backendtrafficpolicy.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/fake/fake_apisx_client.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/fake/fake_backendtrafficpolicy.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/generated_expansion.go
  pkg/client/informers/externalversions/apisx/v1alpha1/backendtrafficpolicy.go
  pkg/client/informers/externalversions/apisx/v1alpha1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apisx/v1alpha1/backendtrafficpolicy.go
  pkg/client/listers/apisx/v1alpha1/expansion_generated.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/test/cel/backendtrafficpolicy_test.go
  pkg/test/cel/main_test.go
Labels: kind/feature, ok-to-test, approved, release-note, kind/documentation, cncf-cla: yes, lgtm, size/XL, kind/gep

#3653 align API Gateway definition with CNCF Glossary
  site-src/faq.md
  site-src/index.md
Labels: approved, release-note, size/M, kind/documentation, cncf-cla: yes, lgtm

#3663 docs: Fix several MkDocs info and warning messages
  mkdocs.yml
  site-src/overrides/partials/copyright.html
Labels: ok-to-test, approved, release-note-none, size/M, kind/documentation, cncf-cla: yes, lgtm

#3651 v1.2.1 conformance report for Envoy Gateway
  conformance/reports/v1.2.1/envoy-gateway/README.md
  conformance/reports/v1.2.1/envoy-gateway/experimental-v1.3.1-default-report.yaml
Labels: approved, release-note-none, cncf-cla: yes, lgtm, size/L

#3656 fix: turn `allowCredentials` to boolean
  apis/v1/httproute_types.go
  apis/v1/shared_types.go
  apis/v1/zz_generated.deepcopy.go
  applyconfiguration/apis/v1/httpcorsfilter.go
  applyconfiguration/internal/internal.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/bug, ok-to-test, approved, size/S, release-note, cncf-cla: yes, lgtm

#3662 docs: Fix 'mkdocs serve' endless build loop
  .gitignore
  hack/mkdocs-copy-geps.py
  hack/mkdocs-generate-conformance.py
  netlify.toml
Labels: ok-to-test, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm, size/L

#3664 GEP-1713: Move Website GEP Link to Experimental
  mkdocs.yml
Labels: size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#3666 Remove mkdocs-material-extensions from requirements.txt
  requirements.txt
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#3668 fix: add CORS to `HTTPRouteFilterType`
  apis/v1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  pkg/generated/openapi/zz_generated.openapi.go
Labels: kind/bug, ok-to-test, size/XS, approved, release-note, cncf-cla: yes, lgtm

#3676 Update NGINX Gateway Fabric communications
  site-src/implementations.md
Labels: ok-to-test, size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#3601 feat: increase `GRPCRoute` matches limit
  apis/v1/grpcroute_types.go
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
  pkg/test/cel/grpcroute_test.go
Labels: kind/feature, ok-to-test, approved, release-note, size/M, cncf-cla: yes, lgtm

#3616 feat: make `Gateway.Spec.Addresses.Value` optional
  apis/v1/gateway_types.go
  apis/v1/zz_generated.deepcopy.go
  apis/v1beta1/gateway_types.go
  applyconfiguration/apis/v1/gatewayspec.go
  applyconfiguration/apis/v1/gatewayspecaddress.go
  applyconfiguration/internal/internal.go
  applyconfiguration/utils.go
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  conformance/tests/gateway-static-addresses.go
  conformance/utils/kubernetes/apply.go
  conformance/utils/suite/suite.go
  pkg/features/gateway.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/test/cel/gateway_test.go
Labels: kind/feature, ok-to-test, approved, release-note, cncf-cla: yes, lgtm, size/L, kind/gep

#3389 Fix conformance coredns deployment
  conformance/base/manifests.yaml
Labels: kind/bug, ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm, area/conformance

#3667 fix: validate that a method and a wildcard won't appear together
  apis/v1/httproute_types.go
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
Labels: kind/bug, ok-to-test, size/XS, approved, release-note, cncf-cla: yes, lgtm

#3683 CORS GEP-1767 is marked Experimental
  geps/gep-1767/index.md
  geps/gep-1767/metadata.yaml
  mkdocs.yml
Labels: kind/bug, ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm, kind/gep

#3690 Add conformance clarification of skipped tests
  hack/mkdocs-generate-conformance.py
Labels: size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#3682 chore: rename CRDs from xgroup to XCRDs
  apisx/v1alpha1/xbackendtrafficpolicy_types.go
  apisx/v1alpha1/xlistenerset_types.go
  apisx/v1alpha1/zz_generated.deepcopy.go
  apisx/v1alpha1/zz_generated.register.go
  applyconfiguration/apisx/v1alpha1/xbackendtrafficpolicy.go
  applyconfiguration/apisx/v1alpha1/xlistenerset.go
  applyconfiguration/internal/internal.go
  applyconfiguration/utils.go
  config/crd/experimental/gateway.networking.x-k8s.io_backendtrafficpolicies.yaml
  config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
  config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/apisx_client.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/backendtrafficpolicy.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/fake/fake_apisx_client.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/fake/fake_backendtrafficpolicy.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/fake/fake_listenerset.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/fake/fake_xbackendtrafficpolicy.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/fake/fake_xlistenerset.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/listenerset.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/xbackendtrafficpolicy.go
  pkg/client/clientset/versioned/typed/apisx/v1alpha1/xlistenerset.go
  pkg/client/informers/externalversions/apisx/v1alpha1/interface.go
  pkg/client/informers/externalversions/apisx/v1alpha1/xbackendtrafficpolicy.go
  pkg/client/informers/externalversions/apisx/v1alpha1/xlistenerset.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apisx/v1alpha1/backendtrafficpolicy.go
  pkg/client/listers/apisx/v1alpha1/expansion_generated.go
  pkg/client/listers/apisx/v1alpha1/listenerset.go
  pkg/client/listers/apisx/v1alpha1/xbackendtrafficpolicy.go
  pkg/client/listers/apisx/v1alpha1/xlistenerset.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/test/cel/backendtrafficpolicy_test.go
Labels: approved, release-note, kind/cleanup, cncf-cla: yes, lgtm, size/L

#3691 Cleanup CRD generation for X types
  config/crd/experimental/gateway.networking.x-k8s.io_listenersets.yaml
  config/crd/experimental/kustomization.yaml
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#3695 Move Budget settings to new BudgetDetails struct
  apisx/v1alpha1/xbackendtrafficpolicy_types.go
  apisx/v1alpha1/zz_generated.deepcopy.go
  applyconfiguration/apisx/v1alpha1/budgetdetails.go
  applyconfiguration/apisx/v1alpha1/retryconstraint.go
  applyconfiguration/internal/internal.go
  applyconfiguration/utils.go
  config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/test/cel/backendtrafficpolicy_test.go
Labels: approved, release-note, kind/cleanup, cncf-cla: yes, lgtm, size/L

#3696 Update SupportHTTPRouteRequestPercentageMirror to Standard
  pkg/features/httproute.go
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#3692 Removing outdated Experimental Gateway API CRDs
  apis/v1alpha2/backendlbpolicy_types.go
  apis/v1alpha2/zz_generated.deepcopy.go
  apis/v1alpha2/zz_generated.register.go
  applyconfiguration/apis/v1/gatewayaddress.go
  applyconfiguration/apis/v1alpha2/backendlbpolicy.go
  applyconfiguration/apis/v1alpha2/backendlbpolicyspec.go
  applyconfiguration/internal/internal.go
  applyconfiguration/utils.go
  config/crd/experimental/kustomization.yaml
  pkg/client/clientset/versioned/typed/apis/v1alpha2/apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/backendlbpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_apis_client.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/fake/fake_backendlbpolicy.go
  pkg/client/clientset/versioned/typed/apis/v1alpha2/generated_expansion.go
  pkg/client/informers/externalversions/apis/v1alpha2/backendlbpolicy.go
  pkg/client/informers/externalversions/apis/v1alpha2/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/apis/v1alpha2/backendlbpolicy.go
  pkg/client/listers/apis/v1alpha2/expansion_generated.go
  pkg/generated/openapi/zz_generated.openapi.go
  pkg/test/cel/backendlbpolicy_test.go
Labels: approved, release-note, kind/cleanup, cncf-cla: yes, lgtm, size/XL

#3702 Bumping k8s dependencies to v1.32.3
  apis/v1/zz_generated.register.go
  apis/v1alpha2/zz_generated.register.go
  apis/v1alpha3/zz_generated.register.go
  apis/v1beta1/zz_generated.register.go
  apisx/v1alpha1/zz_generated.register.go
  go.mod
  go.sum
  hack/update-clientset.sh
Labels: approved, release-note-none, size/M, kind/cleanup, cncf-cla: yes, lgtm

#3703 GEP 3388 XBackendTrafficPolicy API Documentation
  Makefile
  mkdocs.yml
  site-src/api-types/backendtrafficpolicy.md
  site-src/reference/specx.md
Labels: ok-to-test, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm, size/L

#3704 Bumping version to v1.3.0-rc.1
  CHANGELOG/1.3-CHANGELOG.md
  config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
  config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
  config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
  config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
  config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
  config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
  config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
  config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
  config/crd/standard/gateway.networking.k8s.io_gateways.yaml
  config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
  config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
  config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
  pkg/consts/consts.go
Labels: size/XS, approved, release-note-none, kind/documentation, cncf-cla: yes, lgtm

#3705 Removing BackendLBPolicy CRD
  config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#3710 fix(features): GatewayInfrastructure
  pkg/features/gateway.go
Labels: kind/bug, size/XS, approved, release-note, cncf-cla: yes, lgtm, area/conformance

#3714 chore: PR and issue templates use the new conformance labels
  .github/ISSUE_TEMPLATE/conformance-test.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/XS, approved, release-note-none, kind/cleanup, cncf-cla: yes, lgtm

#3716 fix(report): broken link
  conformance/reports/v1.2.1/envoy-gateway/README.md
Labels: size/XS, approved, release-note-none, cncf-cla: yes, lgtm

#3458 Gep 2907 update - TLS mode and allowed routes
  geps/gep-2907/index.md
Labels: approved, release-note-none, size/M, cncf-cla: yes, lgtm, kind/gep

#3708 conformance-tests: fix flake in ExpectMirroredRequest
  conformance/utils/http/mirror.go
Labels: ok-to-test, size/XS, approved, release-note-none, cncf-cla: yes, lgtm, kind/flake, area/conformance-test, kind/test
